import type { Destination } from "./types";

// Single source of truth za slovenske destinacije.
// 12 najboljših destinacij, pokriva vse regije.
export const DESTINATIONS: Destination[] = [
  {
    id: "bled",
    slug: "bled",
    name: "Bled",
    tagline: "Biser Alp s srednjeveškim gradom in otokom",
    region: "gorenjska",
    type: "lake",
    description:
      "Blejsko jezero s svojim edinstvenim otokom, na katerem stoji cerkev z zvonikom, je najbolj prepoznavna slovenska razglednica. Srednjeveški grad na pečini ponuja panoramske poglede, Vintgarska soteska pa kratek sprehod skozi apnenec ob umirjeni reki. Kremšnita v slaščičarni ob jezeru je obvezen sladki greh.",
    highlights: ["Blejski otok", "Blejski grad", "Vintgarska soteska", "Kremšnita"],
    activities: ["Pletna vožnja do otoka", "Obisk gradu", "Sprehod po soteski", "Plavanje"],
    bestFor: ["romantika", "družina", "fotografija"],
    bestSeason: ["spring", "summer", "autumn"],
    image: "https://sfile.chatglm.cn/images-ppt/65ea408c89ea.jpg",
    coords: { lat: 46.3683, lng: 14.0944 },
    rating: 4.8,
    budget: "€€",
    duration: "1-2 dni",
    costPerPerson: 25,
    featured: true,
  },
  {
    id: "bohinj",
    slug: "bohinj",
    name: "Bohinj",
    tagline: "Divja, nedotaknjena lepota Triglavskega narodnega parka",
    region: "gorenjska",
    type: "lake",
    description:
      "Bohinjsko jezero je večji in bolj divji brat Blejskega jezera, znotraj Triglavskega narodnega parka. Žičnica Vogel ponuja panoramske poglede na Julijce, slap Savica pa je kratek pohod skozi gozd. Idealno za tiste, ki iščejo mir in aktivno naravo.",
    highlights: ["Bohinjsko jezero", "Vogel", "Slap Savica", "Triglavski narodni park"],
    activities: ["Pohodništvo", "Smučanje", "Kajakaštvo", "Žičnica Vogel"],
    bestFor: ["narava", "aktivnosti", "mir"],
    bestSeason: ["spring", "summer", "autumn", "winter"],
    image: "https://sfile.chatglm.cn/images-ppt/8a5651a06e91.jpg",
    coords: { lat: 46.2833, lng: 13.8833 },
    rating: 4.7,
    budget: "€",
    duration: "1-2 dni",
    costPerPerson: 15,
    featured: true,
  },
  {
    id: "ljubljana",
    slug: "ljubljana",
    name: "Ljubljana",
    tagline: "Zelena, ustvarjalna prestolnica z zmajevim mostom",
    region: "osrednja",
    type: "city",
    description:
      "Ljubljana je majhna, a živahna prestolnica, kjer se mešata srednjeveška arhitektura in sodobna kulinarična scena. Ljubljanski grad nudi panoramski pogled, Prešernov trg z zmajevim mostom je srce mesta, ob Ljubljanici pa se odvija kava in klepet.",
    highlights: ["Ljubljanski grad", "Zmajev most", "Prešernov trg", "Tivoli park"],
    activities: ["Obisk gradu", "Sprehod po starem mestu", "Kulinarična tura", "Kolo ob Ljubljanici"],
    bestFor: ["kultura", "hrana", "mesto"],
    bestSeason: ["spring", "summer", "autumn"],
    image: "https://sfile.chatglm.cn/images-ppt/06a0b01bbd2d.jpg",
    coords: { lat: 46.0569, lng: 14.5058 },
    rating: 4.6,
    budget: "€",
    duration: "2 dni",
    costPerPerson: 20,
    featured: true,
  },
  {
    id: "postojna",
    slug: "postojnska-jama",
    name: "Postojnska jama",
    tagline: "24 km podzemnih rovov in vilinsko kraljestvo kapnikov",
    region: "kras",
    type: "cave",
    description:
      "Postojnska jama je največji turistični jamski sistem v Evropi z edinstvenim podzemnim vlakcem. V njej bivala tudi človeška ribica — endemit, ki je navdihnil legende o zmajevih mladičih. Predjamski grad, vklesan v 123-metrsko pečino, je le 9 km stran.",
    highlights: ["Podzemno vlakec", "Kapniki", "Človeška ribica", "Predjamski grad"],
    activities: ["Jamska tura z vlakcem", "Obisk Predjamskega gradu", "Fotografija"],
    bestFor: ["družina", "avantura", "narava"],
    bestSeason: ["spring", "summer", "autumn", "winter"],
    image: "https://sfile.chatglm.cn/images-ppt/48f79b432fcb.jpg",
    coords: { lat: 45.7845, lng: 14.2045 },
    rating: 4.7,
    budget: "€€",
    duration: "1 dan",
    costPerPerson: 30,
    featured: true,
  },
  {
    id: "piran",
    slug: "piran",
    name: "Piran",
    tagline: "Slovenske Benetke s kamnitimi uličicami in Tartinijevim trgom",
    region: "primorska",
    type: "coast",
    description:
      "Piran je obmorsko mestece beneškega videza, kjer se ozke uličice stiskajo med kamnitimi hišami. Tartinijev trg, glavni trg z marmornatimi tlaki, je posvečen violinistu Giuseppu Tartiniju. Cerkev sv. Jurija na hribu ponuja pogled na Jadransko morje.",
    highlights: ["Tartinijev trg", "Cerkev sv. Jurija", "Obala", "Stare uličice"],
    activities: ["Sprehod po starem mestu", "Sončni zahod", "Morska hrana", "Obisk solin"],
    bestFor: ["romantika", "kultura", "hrana"],
    bestSeason: ["spring", "summer", "autumn"],
    image: "https://sfile.chatglm.cn/images-ppt/1ca2f342127f.jpg",
    coords: { lat: 45.5233, lng: 13.5676 },
    rating: 4.7,
    budget: "€€",
    duration: "1 dan",
    costPerPerson: 35,
    featured: true,
  },
  {
    id: "soca",
    slug: "reka-soca",
    name: "Reka Soča",
    tagline: "Smaragdna reka med Julijci za adrenalinske avanture",
    region: "gorenjska",
    type: "river",
    description:
      "Soča je ena redkih rek, ki ohranja svojo smaragdno barvo skozi vse leto. Vije se skozi Tolmin in Bovec, kjer ponuja vrhunsko rafting, kajakaštvo in canyoning. Vmes so korita Soče — naravni bazeni, vrezani v apnenec, idealni za poletno osvežitev.",
    highlights: ["Korita Soče", "Bovec", "Tolmin", "Trdnjava Kluže"],
    activities: ["Rafting", "Kajakaštvo", "Canyoning", "Zip-line"],
    bestFor: ["adrenalin", "narava", "poletje"],
    bestSeason: ["spring", "summer", "autumn"],
    image: "https://sfile.chatglm.cn/images-ppt/5f720abe0af2.jpg",
    coords: { lat: 46.3447, lng: 13.7332 },
    rating: 4.8,
    budget: "€€",
    duration: "2-3 dni",
    costPerPerson: 40,
    featured: true,
  },
  {
    id: "triglav",
    slug: "triglav",
    name: "Triglav",
    tagline: "2864 m visok simbol naroda z neštetimi potmi",
    region: "gorenjska",
    type: "mountain",
    description:
      "Triglav je najvišji vrh Slovenije in narodni simbol, ki krasa državni grb. Vzpon zahteva tehnično pohodništvo, a ob pogoju dobre priprave je dosegljiv v enih ali dveh dneh. Na vrhu stoji Aljažev stolp — najvišje ležeče zatočišče v državi.",
    highlights: ["Vrh 2864 m", "Aljažev stolp", "Triglavska roža", "Pohodništvo"],
    activities: ["Pohodništvo", "Alpinizem", "Fotografija"],
    bestFor: ["avantura", "pohodništvo", "narava"],
    bestSeason: ["summer", "autumn"],
    image: "https://sfile.chatglm.cn/images-ppt/f1fdf5ca02fe.jpg",
    coords: { lat: 46.3794, lng: 13.8462 },
    rating: 4.9,
    budget: "€",
    duration: "2 dni",
    costPerPerson: 15,
    featured: false,
  },
  {
    id: "kobarid",
    slug: "kobarid",
    name: "Kobarid",
    tagline: "Zgodovina, Soška fronta in kulinarika v eni vasi",
    region: "gorenjska",
    type: "city",
    description:
      "Kobarid je vasica ob Soči, znana po Kobaridskem muzeju, ki dokumentira krvavo Soško fronto prve svetovne vojne. Napoleonov most čez Sočo in Kolovrat ponujata panoramske poglede. Hiša Franko, ena najboljših restavrac v regiji, prinaša sodobno tolminsko kuhinjo.",
    highlights: ["Kobaridski muzej", "Napoleonov most", "Kolovrat", "Hiša Franko"],
    activities: ["Muzej", "Pohodništvo", "Kulinarična izkušnja", "Kolo ob Soči"],
    bestFor: ["zgodovina", "hrana", "narava"],
    bestSeason: ["spring", "summer", "autumn"],
    image: "https://sfile.chatglm.cn/images-ppt/518f556394ec.jpeg",
    coords: { lat: 46.2453, lng: 13.5864 },
    rating: 4.5,
    budget: "€€",
    duration: "1 dan",
    costPerPerson: 25,
    featured: false,
  },
  {
    id: "maribor",
    slug: "maribor",
    name: "Maribor",
    tagline: "Drugo največje mesto z najstarejšo trto na svetu",
    region: "stajerska",
    type: "city",
    description:
      "Maribor leži ob Dravi, obkrožen z vinogradi Pohorja. Stara trta, stara več kot 400 let, je vpisana v Guinnessovo knjigo rekordov. Mesto ponuja živahno staro mestno jedro, vinogradniške lance Pohorja in smučanje pozimi.",
    highlights: ["Stara trta", "Pohorje", "Glavni trg", "Vinogradništvo"],
    activities: ["Obisk Stare trte", "Smučanje Pohorje", "Vinska degustacija", "Staro mesto"],
    bestFor: ["kultura", "vino", "smučanje"],
    bestSeason: ["spring", "summer", "autumn", "winter"],
    image: "https://sfile.chatglm.cn/images-ppt/c1a887b9c8c2.jpg",
    coords: { lat: 46.5547, lng: 15.6459 },
    rating: 4.4,
    budget: "€",
    duration: "1-2 dni",
    costPerPerson: 20,
    featured: false,
  },
  {
    id: "portoroz",
    slug: "portoroz",
    name: "Portorož",
    tagline: "Slovensko obmorsko letovišče s Casino in wellness",
    region: "primorska",
    type: "coast",
    description:
      "Portorož je najbolj znano slovensko obmorsko letovišče z dolgo peščeno plažo, hoteli z wellness centri in Casinojem. Obalne sprehajališče povezuje Portorož s Piranom, soline Sečovlje pa nudijo edinstveno naravno izkušnjo in wellness z blatom.",
    highlights: ["Plaža", "Casino", "Soline Sečovlje", "Wellness"],
    activities: ["Plavanje", "Wellness", "Igre na srečo", "Kolo ob morju"],
    bestFor: ["poletje", "wellness", "družina"],
    bestSeason: ["spring", "summer", "autumn"],
    image: "https://sfile.chatglm.cn/images-ppt/ce5079515d70.jpg",
    coords: { lat: 45.5142, lng: 13.5922 },
    rating: 4.3,
    budget: "€€€",
    duration: "2-3 dni",
    costPerPerson: 60,
    featured: false,
  },
  {
    id: "vintgar",
    slug: "vintgarska-soteska",
    name: "Vintgarska soteska",
    tagline: "Kratek sprehod skozi apnenec ob umirjeni reki",
    region: "gorenjska",
    type: "gorge",
    description:
      "Vintgarska soteska je 1,6 km dolga soteska ob reki Radovni, le 4 km od Bleda. Lesene poti vodijo ob kristalno čisti vodi, mimo slapa in naravnih bazenov. Sprehod traja približno eno uro in je primeren za vse starosti.",
    highlights: ["Slap Šum", "Lesene poti", "Kristalna voda", "Naravni bazeni"],
    activities: ["Sprehod", "Fotografija", "Opazovanje narave"],
    bestFor: ["družina", "narava", "fotografija"],
    bestSeason: ["spring", "summer", "autumn"],
    image: "https://sfile.chatglm.cn/images-ppt/13c851e9bce1.jpg",
    coords: { lat: 46.4, lng: 14.1167 },
    rating: 4.6,
    budget: "€",
    duration: "1 dan",
    costPerPerson: 10,
    featured: false,
  },
  {
    id: "rogaska",
    slug: "rogaska-slatina",
    name: "Rogaška Slatina",
    tagline: "Najstarejše slovensko zdravilišče z mineralno vodo",
    region: "stajerska",
    type: "spa",
    description:
      "Rogaška Slatina je elegantno zdravilišče z 400-letno tradicijo, znano po mineralni vodi Donat Mg z najvišjo vsebnostjo magnezija na svetu. Secesijska arhitektura, parki in wellness centri nudijo sprostitev skozi vse leto.",
    highlights: ["Donat Mg", "Secesijska arhitektura", "Grand hotel", "Wellness"],
    activities: ["Wellness", "Pitje mineralne vode", "Sprehodi po parku", "Masaže"],
    bestFor: ["wellness", "sprostitev", "zdravje"],
    bestSeason: ["spring", "summer", "autumn", "winter"],
    image: "https://sfile.chatglm.cn/images-ppt/3f259fe258bb.jpg",
    coords: { lat: 46.3231, lng: 15.6422 },
    rating: 4.4,
    budget: "€€€",
    duration: "2 dni",
    costPerPerson: 80,
    featured: false,
  },
  // === ŠTAJERSKA — dodatne destinacije ===
  {
    id: "ptuj",
    slug: "ptuj",
    name: "Ptuj",
    tagline: "Najstarejše mesto v Sloveniji z rimsko zgodovino",
    region: "stajerska",
    type: "city",
    description:
      "Ptuj je najstarejše zabeleženo mesto v Sloveniji, ustanovljeno v rimski dobi kot Poetovio. Srednjeveški grad na hribu ponuja panoramski pogled na Dravo, staro mestno jedro pa ohranja baročno arhitekturo. Poznan po Kurentovanju — največjem pustnem festivalu v Srednji Evropi.",
    highlights: ["Ptujski grad", "Rimske izkopanine", "Kurentovanje", "Drava"],
    activities: ["Obisk gradu", "Sprehod po starem mestu", "Pustni festival", "Sprehod ob Dravi"],
    bestFor: ["kultura", "zgodovina", "festival"],
    bestSeason: ["spring", "summer", "autumn", "winter"],
    image: "https://sfile.chatglm.cn/images-ppt/217561ec8261.jpg",
    coords: { lat: 46.4197, lng: 15.867 },
    rating: 4.5,
    budget: "€",
    duration: "1 dan",
    costPerPerson: 18,
    featured: false,
  },
  {
    id: "celje",
    slug: "celje",
    name: "Celje",
    tagline: "Nekdanja prestolnica grofov Celjskih z impresivnim gradom",
    region: "stajerska",
    type: "city",
    description:
      "Celje je tretje največje mesto v Sloveniji, znano po srednjeveškem gradu Celjskih grofov — nekdaj najvplivnejšega plemiškega rodu na Slovenskem. Stari trg ohranja baročne fasade, ob Savinji pa se vije sprehajalna pot.",
    highlights: ["Stari grad Celje", "Stari trg", "Savinja", "Pokrajinski muzej"],
    activities: ["Obisk gradu", "Sprehod po starem mestu", "Muzej", "Kolo ob Savinji"],
    bestFor: ["kultura", "zgodovina", "družina"],
    bestSeason: ["spring", "summer", "autumn"],
    image: "https://sfile.chatglm.cn/images-ppt/9cd8cbe421b4.jpg",
    coords: { lat: 46.2389, lng: 15.2675 },
    rating: 4.3,
    budget: "€",
    duration: "1 dan",
    costPerPerson: 15,
    featured: false,
  },
  // === PRIMORSKA — dodatne destinacije ===
  {
    id: "nova-gorica",
    slug: "nova-gorica",
    name: "Nova Gorica",
    tagline: "Mesto vrtnic na meji z Italijo",
    region: "primorska",
    type: "city",
    description:
      "Nova Gorica je mlado mesto zgrajeno po 2. svetovni vojni, znano kot 'mesto vrtnic'. Meji na italijansko Gorico — edina evropska mesti ki si delita trg (Trg Evrope). Casino, parki in mediteranski ambient.",
    highlights: ["Trg Evrope", "Park vrtnic", "Casino Perla", "Solkan most"],
    activities: ["Sprehod po parku", "Igre na srečo", "Mejni sprehod v Italijo", "Kolo ob Soči"],
    bestFor: ["wellness", "mesto", "poletje"],
    bestSeason: ["spring", "summer", "autumn"],
    image: "https://sfile.chatglm.cn/images-ppt/4214e73010ea.jpg",
    coords: { lat: 45.9636, lng: 13.6414 },
    rating: 4.2,
    budget: "€€",
    duration: "1 dan",
    costPerPerson: 30,
    featured: false,
  },
  // === KOROŠKA ===
  {
    id: "slovenj-gradec",
    slug: "slovenj-gradec",
    name: "Slovenj Gradec",
    tagline: "Alpsko mestece z bogato glasbeno tradicijo",
    region: "koroska",
    type: "city",
    description:
      "Slovenj Gradec je zgodovinsko mestece na severu Slovenije, obkroženo z Koroškimi Alpami. Znan po Dvorani slovenskih glasbenikov in rojstnem kraju Hugo Wolfa. Idealna izhodišča za pohode na Pohorje in Uršljo goro.",
    highlights: ["Dvorana slovenskih glasbenikov", "Stari trg", "Pohorje", "Uršlja gora"],
    activities: ["Pohodništvo", "Glasbeni koncerti", "Sprehod po starem mestu", "Smučanje"],
    bestFor: ["narava", "kultura", "mir"],
    bestSeason: ["spring", "summer", "autumn", "winter"],
    image: "https://sfile.chatglm.cn/images-ppt/dd232cc0e58b.jpg",
    coords: { lat: 46.5131, lng: 15.0864 },
    rating: 4.4,
    budget: "€",
    duration: "1 dan",
    costPerPerson: 15,
    featured: false,
  },
  {
    id: "dravograd",
    slug: "dravograd",
    name: "Dravograd",
    tagline: "Tromeja rek Drave, Meže in Mislinje",
    region: "koroska",
    type: "river",
    description:
      "Dravograd je majhno mestece na severu Slovenije kjer se stikajo tri reke — Drava, Meža in Mislinja. Obkrožen z gozdovi Kozjaka in Pohorja. Hidroelektrarna na Dravi in pohodniške poti ob reki.",
    highlights: ["Sotoče treh rek", "HE Dravograd", "Kozjak", "Pohodništvo"],
    activities: ["Pohodništvo", "Ribolov", "Kolo ob Dravi", "Fotografija narave"],
    bestFor: ["narava", "mir", "pohodništvo"],
    bestSeason: ["spring", "summer", "autumn"],
    image: "https://sfile.chatglm.cn/images-ppt/ffe5d13f2516.jpg",
    coords: { lat: 46.5864, lng: 15.0019 },
    rating: 4.1,
    budget: "€",
    duration: "1 dan",
    costPerPerson: 10,
    featured: false,
  },
  // === PREKMURJE ===
  {
    id: "murska-sobota",
    slug: "murska-sobota",
    name: "Murska Sobota",
    tagline: "Center Prekmurja z gradom ob jezeru",
    region: "prekmurje",
    type: "city",
    description:
      "Murska Sobota je središče Prekmurja — ravne panonske pokrajine na severovzhodu Slovenije. Grad Murska Sobota ob istoimenskem jezeru hrani Pokrajinski muzej. Znana po prekmurski gibanici in bučnem olju.",
    highlights: ["Grad Murska Sobota", "Sobotoško jezero", "Prekmurska gibanica", "Pokrajinski muzej"],
    activities: ["Obisk gradu", "Sprehod ob jezeru", "Kulinarične izkušnje", "Kolo po ravnini"],
    bestFor: ["kultura", "hrana", "družina"],
    bestSeason: ["spring", "summer", "autumn"],
    image: "https://sfile.chatglm.cn/images-ppt/e63eaac243b6.jpg",
    coords: { lat: 46.6667, lng: 16.1667 },
    rating: 4.3,
    budget: "€",
    duration: "1 dan",
    costPerPerson: 18,
    featured: false,
  },
  {
    id: "lendava",
    slug: "lendava",
    name: "Lendava",
    tagline: "Dvojezično mesto z vinogradi in gradom na hribu",
    region: "prekmurje",
    type: "city",
    description:
      "Lendava je najbolj vzhodno mesto v Sloveniji, na meji z Madžarsko. Dvojezično (slovensko-madžarsko) mesto z gradom na hribu, ki ponuja panoramski pogled na vinograde Lendavskih goric. Pridelava vrhunskih belih vin.",
    highlights: ["Grad Lendava", "Vinogradi Lendavskih goric", "Dvojezična kultura", "Vinska klet"],
    activities: ["Vinska degustacija", "Obisk gradu", "Kolo po vinogradih", "Mejni sprehod"],
    bestFor: ["vino", "kultura", "hrana"],
    bestSeason: ["spring", "summer", "autumn"],
    image: "https://sfile.chatglm.cn/images-ppt/e3f47a3c4190.jpg",
    coords: { lat: 46.5564, lng: 16.4544 },
    rating: 4.4,
    budget: "€€",
    duration: "1 dan",
    costPerPerson: 25,
    featured: false,
  },
  // === DOLENJSKA ===
  {
    id: "novo-mesto",
    slug: "novo-mesto",
    name: "Novo mesto",
    tagline: "Dolenjska prestolnica ob reki Krki",
    region: "dolenjska",
    type: "city",
    description:
      "Novo mesto je središče Dolenjske, zgrajeno v okljuku reke Krke. Stari trg z glavno ulico ohranja srednjeveški značaj. Znana po cvičku — tradicionalnem dolenjskem vinu, in po arheoloških najdbah halštatske kulture.",
    highlights: ["Stari trg", "Reka Krka", "Cviček", "Arheološki muzej"],
    activities: ["Sprehod po starem mestu", "Vinska degustacija", "Kolo ob Krki", "Muzej"],
    bestFor: ["kultura", "vino", "narava"],
    bestSeason: ["spring", "summer", "autumn"],
    image: "https://sfile.chatglm.cn/images-ppt/8f3aa8e1a6c3.jpg",
    coords: { lat: 45.8039, lng: 15.1686 },
    rating: 4.4,
    budget: "€",
    duration: "1-2 dni",
    costPerPerson: 20,
    featured: false,
  },
  {
    id: "otocec",
    slug: "otocec",
    name: "Otočec",
    tagline: "Edini slovenski grad na otoku reke",
    region: "dolenjska",
    type: "castle",
    description: "Otočec je edini slovenski grad na otoku, obkrožen z reko Krko. Danes luksuzen hotel z golf igriščem in wellnessom. Romantično okolje za pare in izhodišče za kolesarjenje ob Krki.",
    highlights: ["Grad na otoku", "Reka Krka", "Golf", "Wellness"],
    activities: ["Golf", "Wellness", "Kolo ob Krki", "Romantični večerja"],
    bestFor: ["romantika", "wellness", "mir"],
    bestSeason: ["spring", "summer", "autumn"],
    image: "https://sfile.chatglm.cn/images-ppt/a50accb13d5e.jpg",
    coords: { lat: 45.6833, lng: 15.1833 },
    rating: 4.6,
    budget: "€€€",
    duration: "1-2 dni",
    costPerPerson: 70,
    featured: false,
  },
  // === BELA KRAJINA ===
  {
    id: "crnomelj",
    slug: "crnomelj",
    name: "Črnomelj",
    tagline: "Srce Bele krajine ob reki Kolpi",
    region: "bela-krajina",
    type: "city",
    description:
      "Črnomelj je središče Bele krajine — tople, mediteransko navdahnjene pokrajine na jugovzhodu Slovenije ob reki Kolpi. Znan po belokranjski pisanici (barvanih pirhih), steljnikih in tradicionalni belokranjski glasbi. Kolpa ponuja najtoplejše kopanje v Sloveniji.",
    highlights: ["Reka Kolpa", "Stari trg", "Belokranjska pisanica", "Steljniki"],
    activities: ["Kopanje v Kolpi", "Sprehod po starem mestu", "Kolo po Beli krajini", "Etnografski muzej"],
    bestFor: ["narava", "poletje", "družina"],
    bestSeason: ["spring", "summer", "autumn"],
    image: "https://sfile.chatglm.cn/images-ppt/425509152cd6.jpg",
    coords: { lat: 45.5747, lng: 15.1892 },
    rating: 4.3,
    budget: "€",
    duration: "1-2 dni",
    costPerPerson: 15,
    featured: false,
  },
];

// Pomožne funkcije za iskanje
export function getDestinationById(id: string): Destination | undefined {
  return DESTINATIONS.find((d) => d.id === id);
}

export function getFeaturedDestinations(): Destination[] {
  return DESTINATIONS.filter((d) => d.featured);
}

export function getDestinationsByRegion(region: string): Destination[] {
  return DESTINATIONS.filter((d) => d.region === region);
}

export const REGIONS: { value: string; label: string }[] = [
  { value: "gorenjska", label: "Gorenjska" },
  { value: "primorska", label: "Primorska" },
  { value: "osrednja", label: "Osrednja Slovenija" },
  { value: "kras", label: "Kras" },
  { value: "stajerska", label: "Štajerska" },
  { value: "koroska", label: "Koroška" },
  { value: "prekmurje", label: "Prekmurje" },
  { value: "dolenjska", label: "Dolenjska" },
  { value: "bela-krajina", label: "Bela krajina" },
];

export const INTERESTS: { value: string; label: string; icon: string }[] = [
  { value: "narava", label: "Narava", icon: "🌿" },
  { value: "kultura", label: "Kultura", icon: "🏛️" },
  { value: "hrana", label: "Hrana & vino", icon: "🍷" },
  { value: "avantura", label: "Avantura", icon: "🧗" },
  { value: "adrenalin", label: "Adrenalin", icon: "⚡" },
  { value: "romantika", label: "Romantika", icon: "❤️" },
  { value: "družina", label: "Družina", icon: "👨‍👩‍👧" },
  { value: "wellness", label: "Wellness", icon: "💆" },
];
