import { db } from "@/lib/db";

// ============================================================================
// SEED EXPAND — doda 15 novih listings + 20 novih products + 20 novih experiences
// v obstoječo bazo. Preverja po slug-u, da ne duplicira.
//
// Po poganjanju:
//   - Listings:  10 obstoječih + 15 novih = 25
//   - Products:  8 obstoječih + 20 novih  = 28
//   - Experiences: 8 obstoječih + 20 novih = 28
// ============================================================================

// ----------------------------------------------------------------------------
// 15 NOVIH LISTINGS — pokrivajo vse 9 regij, mix kategorij
// ----------------------------------------------------------------------------
const newListings = [
  // === GORENJSKA ===
  {
    name: "Hotel Triglav Bled",
    slug: "hotel-triglav-bled",
    description: "Elegantni 4* boutique hotel s pogledom na Blejsko jezero in Triglav.",
    longDescription:
      "Hotel Triglav Bled je eleganten boutique hotel z restavracijo z Michelin zvezdico, le 5 min sprehoda od Blejskega jezera. Ponuja panoramske poglede na Triglav in Julijce, wellness center ter vrhunsko kulinarično izkušnjo z lokalnimi sestavinami.",
    category: "hotel",
    destinationId: "bled",
    destinationName: "Bled",
    address: "Veslaška promenada 11, 4260 Bled",
    phone: "+386 4 529 2500",
    email: "info@hoteltriglavbled.si",
    website: "https://www.hoteltriglavbled.si",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200&h=800&fit=crop&q=80",
      "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1200&h=800&fit=crop&q=80",
    ]),
    plan: "premium",
    featured: true,
    verified: true,
    rating: 4.8,
    reviewCount: 612,
    priceRange: "€€€",
    openingHours: "24/7 recepcija",
    specialties: JSON.stringify([
      "Michelin restavracija",
      "Wellness",
      "Pogled na jezero",
      "Boutique",
    ]),
    ownerEmail: "info@hoteltriglavbled.si",
  },
  {
    name: "Hiša Franko",
    slug: "hisa-franko",
    description: "Slovenska restavracija z Michelin zvezdico v Kobaridu ob Soči.",
    longDescription:
      "Hiša Franko vodi chef Ana Roš, ki je bila leta 2017 razglašena za najboljšo žensko chef na svetu. Restavracija ponuja inovativno tolminsko kuhinjo z lokalnimi sestavinami in 7-urno degustacijsko izkušnjo. Vinska klet z več kot 1200 etiketami.",
    category: "restaurant",
    destinationId: "kobarid",
    destinationName: "Kobarid",
    address: "Staro Selo 1, 5222 Kobarid",
    phone: "+386 5 389 4120",
    email: "info@hisafranko.si",
    website: "https://www.hisafranko.com",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1200&h=800&fit=crop&q=80",
      "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1200&h=800&fit=crop&q=80",
    ]),
    plan: "enterprise",
    featured: true,
    verified: true,
    rating: 4.9,
    reviewCount: 389,
    priceRange: "€€€",
    openingHours: "Sre-Ned 18:00-23:00",
    specialties: JSON.stringify([
      "Michelin zvezda",
      "Degustacijski meni",
      "Lokalne sestavine",
      "Vinska klet",
    ]),
    ownerEmail: "info@hisafranko.si",
  },
  // === PRIMORSKA ===
  {
    name: "Hotel Grand Plaza Portorož",
    slug: "hotel-grand-plaza-portoroz",
    description: "Luksuzen 5* hotel v Portorožu z zasebno plažo in wellnessom.",
    longDescription:
      "Hotel Grand Plaza je sodoben 5* luksuzen hotel ob morju v Portorožu. Nudi zasebno plažo, wellness center znotraj Shortino terme, rooftop bazen z morsko vodo in restavracijo z mediteransko kuhinjo. Idealen za romantiko in wellness oddih.",
    category: "hotel",
    destinationId: "piran",
    destinationName: "Piran",
    address: "Obala 73, 6320 Portorož",
    phone: "+386 5 690 1100",
    email: "info@grandplaza-portoroz.si",
    website: "https://www.grandplaza-portoroz.si",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=1200&h=800&fit=crop&q=80",
      "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=1200&h=800&fit=crop&q=80",
    ]),
    plan: "enterprise",
    featured: true,
    verified: true,
    rating: 4.7,
    reviewCount: 891,
    priceRange: "€€€",
    openingHours: "24/7 recepcija",
    specialties: JSON.stringify([
      "Morski pogled",
      "Rooftop bazen",
      "Wellness",
      "Zasebna plaža",
    ]),
    ownerEmail: "info@grandplaza-portoroz.si",
  },
  {
    name: "Vinska klet Golje",
    slug: "vinska-klet-golje",
    description: "Tradicionalna vinska klet v Vipavski dolini z degustacijami in turji.",
    longDescription:
      "Vinska klet Golje je družinska klet v Vipavski dolini s 100-letno tradicijo. Pridelujejo avtohtone sorte kot so pinela, zelen in klarnica. Ponujajo vodene degustacije s sirevi in pršutom, oglede vinogradov in kleti.",
    category: "restaurant",
    destinationId: "nova-gorica",
    destinationName: "Nova Gorica",
    address: "Golje 12, 5273 Vipava",
    phone: "+386 5 368 7200",
    email: "info@klet-golje.si",
    website: "https://www.klet-golje.si",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=1200&h=800&fit=crop&q=80",
      "https://images.unsplash.com/photo-1547595628-c61a29f496f0?w=1200&h=800&fit=crop&q=80",
    ]),
    plan: "premium",
    featured: false,
    verified: true,
    rating: 4.6,
    reviewCount: 234,
    priceRange: "€€",
    openingHours: "Pon-Sob 11:00-22:00",
    specialties: JSON.stringify([
      "Avtohtone sorte",
      "Degustacije",
      "Vipavska dolina",
      "Družinska tradicija",
    ]),
    ownerEmail: "info@klet-golje.si",
  },
  {
    name: "Gostilna Ribič",
    slug: "gostilna-ribic",
    description: "Tradicionalna gostilna v Piranu z najboljšo morsko hrano.",
    longDescription:
      "Gostilna Ribič je priljubljena piranska gostilna ob Tartinijevem trgu, znana po sveži ribi in morskih sadežih. Dnevno ulovljene sipe, brancini in tune pripravljajo na žaru ali v solatah. Priporočena rezervacija v sezoni.",
    category: "restaurant",
    destinationId: "piran",
    destinationName: "Piran",
    address: "Židovski trg 4, 6330 Piran",
    phone: "+386 5 673 2244",
    email: "info@gostilna-ribic.si",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=1200&h=800&fit=crop&q=80",
    ]),
    plan: "free",
    featured: false,
    verified: false,
    rating: 4.4,
    reviewCount: 412,
    priceRange: "€€",
    openingHours: "Pon-Ned 11:00-23:00",
    specialties: JSON.stringify(["Sveža riba", "Morski sadeži", "Center mesta"]),
  },
  // === OSREDNJA ===
  {
    name: "Hotel City Ljubljana",
    slug: "hotel-city-ljubljana",
    description: "Sodoben 4* hotel v središču Ljubljane, 3 min od Prešernovega trga.",
    longDescription:
      "Hotel City Ljubljana je sodoben 4* hotel v središču mesta z odlično lokacijo za raziskovanje Ljubljane. Nudi udobne sobe, rooftop restavracijo z mestnim pogledom, fitness in brezplačno parkirišče. 5 min do žičnice na Ljubljanski grad.",
    category: "hotel",
    destinationId: "ljubljana",
    destinationName: "Ljubljana",
    address: "Dalmatinova 15, 1000 Ljubljana",
    phone: "+386 1 425 6000",
    email: "info@hotelcity-ljubljana.si",
    website: "https://www.hotelcity-ljubljana.si",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=1200&h=800&fit=crop&q=80",
      "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=1200&h=800&fit=crop&q=80",
    ]),
    plan: "premium",
    featured: true,
    verified: true,
    rating: 4.5,
    reviewCount: 756,
    priceRange: "€€",
    openingHours: "24/7 recepcija",
    specialties: JSON.stringify([
      "Center mesta",
      "Rooftop restavracija",
      "Fitness",
      "Parkirišče",
    ]),
    ownerEmail: "info@hotelcity-ljubljana.si",
  },
  {
    name: "Restavracija As",
    slug: "restavracija-as",
    description: "Michelin priporočena restavracija s sodobno slovensko kuhinjo v Ljubljani.",
    longDescription:
      "Restavracija As vodi chef Tomaž Kavčič, eden pionirjev sodobne slovenske kuhinje. Ponuja avtorske menije z lokalnimi sestavinami, ki združujejo alpsko, sredozemsko in panonsko tradicijo. Vinska karta z več kot 300 slovenskimi vineti.",
    category: "restaurant",
    destinationId: "ljubljana",
    destinationName: "Ljubljana",
    address: "Ciril-Metodov trg 3, 1000 Ljubljana",
    phone: "+386 1 425 8822",
    email: "info@restavracija-as.si",
    website: "https://www.restavracija-as.si",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=1200&h=800&fit=crop&q=80",
      "https://images.unsplash.com/photo-1547595628-c61a29f496f0?w=1200&h=800&fit=crop&q=80",
    ]),
    plan: "enterprise",
    featured: true,
    verified: true,
    rating: 4.7,
    reviewCount: 523,
    priceRange: "€€€",
    openingHours: "Pon-Sob 12:00-23:00",
    specialties: JSON.stringify([
      "Michelin priporočilo",
      "Avtorski meni",
      "Vinska karta",
      "Slovenska kuhinja",
    ]),
    ownerEmail: "info@restavracija-as.si",
  },
  // === KRAS ===
  {
    name: "Jamska kavarna Postojna",
    slug: "jamska-kavarna-postojna",
    description: "Prijetna kavarna ob Postojnski jami s pršutom in teranom.",
    longDescription:
      "Jamska kavarna je priljubljena postojanka ob vhodu v Postojnsko jamo. Ponujajo kraški pršut, sir, teran in lokalne olive. Po ogledu jame je idealna za sprostitev s kozarcem vina in tradicionalnimi prigrizki.",
    category: "bar",
    destinationId: "postojna",
    destinationName: "Postojnska jama",
    address: "Jamska cesta 28, 6230 Postojna",
    phone: "+386 5 700 0300",
    email: "info@jamska-kavarna.si",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=1200&h=800&fit=crop&q=80",
    ]),
    plan: "free",
    featured: false,
    verified: false,
    rating: 4.2,
    reviewCount: 178,
    priceRange: "€",
    openingHours: "Pon-Ned 9:00-21:00",
    specialties: JSON.stringify([
      "Kraški pršut",
      "Teran",
      "Ob jami",
      "Lokalno vino",
    ]),
  },
  // === ŠTAJERSKA ===
  {
    name: "Kmečko gospodarstvo Novak",
    slug: "kmecko-gospodarstvo-novak",
    description: "Družinska kmetija v Ptuju z ekološkimi izdelki in kmetijskim turizmom.",
    longDescription:
      "Kmečko gospodarstvo Novak je družinska kmetija v Ptuju z ekološko pridelavo. Ponujajo domače sire, mesne izdelke, marmelade in olive. Tudi kmetijski turizem z nočitvijo v prenovljeni kmetijski hiši in vodenimi ogledi kmetije.",
    category: "shop",
    destinationId: "ptuj",
    destinationName: "Ptuj",
    address: "Videm pri Ptuju 23, 2251 Videm pri Ptuju",
    phone: "+386 2 787 1100",
    email: "info@kmetija-novak.si",
    website: "https://www.kmetija-novak.si",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&h=800&fit=crop&q=80",
      "https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=1200&h=800&fit=crop&q=80",
    ]),
    plan: "premium",
    featured: false,
    verified: true,
    rating: 4.7,
    reviewCount: 145,
    priceRange: "€€",
    openingHours: "Pon-Sob 8:00-19:00",
    specialties: JSON.stringify([
      "Ekološka pridelava",
      "Domači siri",
      "Kmetijski turizem",
      "Marmelade",
    ]),
    ownerEmail: "info@kmetija-novak.si",
  },
  {
    name: "Pri Starem Piskru",
    slug: "pri-starem-piskru",
    description: "Tradicionalna celjska gostilna s štajersko kuhinjo in lokalnimi vini.",
    longDescription:
      "Gostilna Pri Starem Piskru je tradicionalna celjska restavracija znana po štajerski kuhinji — fazanu, žlikrofih, ajdovih žgancih in lokalnih vinih. Sproščen ambient v srednjeveških obokih starega mesta.",
    category: "restaurant",
    destinationId: "celje",
    destinationName: "Celje",
    address: "Trg celjskih knezov 7, 3000 Celje",
    phone: "+386 3 425 3344",
    email: "info@stari-pisker-celje.si",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1200&h=800&fit=crop&q=80",
    ]),
    plan: "free",
    featured: false,
    verified: false,
    rating: 4.3,
    reviewCount: 267,
    priceRange: "€€",
    openingHours: "Pon-Sob 11:00-22:00",
    specialties: JSON.stringify([
      "Štajerska kuhinja",
      "Žlikrofi",
      "Srednjeveški ambient",
      "Lokalna vina",
    ]),
  },
  // === KOROŠKA ===
  {
    name: "Hotel Slovenj Gradec",
    slug: "hotel-slovenj-gradec",
    description: "Sodoben 4* hotel v Slovenj Gradcu z wellnessom in Pohorjem na dosegu roke.",
    longDescription:
      "Hotel Slovenj Gradec je sodoben 4* hotel v zgodovinskem mestecu ob vznožju Uršlje gore. Ponuja wellness center, restavracijo z lokalnimi jedmi in odlično izhodišče za pohode po Pohorju in Koroških Alpah.",
    category: "hotel",
    destinationId: "slovenj-gradec",
    destinationName: "Slovenj Gradec",
    address: "Trg sv. Elizabete 6, 2380 Slovenj Gradec",
    phone: "+386 2 881 2200",
    email: "info@hotel-slovenj-gradec.si",
    website: "https://www.hotel-slovenj-gradec.si",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=1200&h=800&fit=crop&q=80",
    ]),
    plan: "premium",
    featured: false,
    verified: true,
    rating: 4.4,
    reviewCount: 198,
    priceRange: "€€",
    openingHours: "24/7 recepcija",
    specialties: JSON.stringify([
      "Wellness",
      "Izhodišče za Pohorje",
      "Lokalna kuhinja",
      "Družinski prijazen",
    ]),
    ownerEmail: "info@hotel-slovenj-gradec.si",
  },
  // === PREKMURJE ===
  {
    name: "Prekmurska kmetija",
    slug: "prekmurska-kmetija",
    description: "Tradicionalna prekmurska kmetija z bučnim oljem, gibanico in domačimi izdelki.",
    longDescription:
      "Prekmurska kmetija je predstavnik tradicionalnega prekmurskega kmetijstva. Pridelujejo bučno olje, marmelade, sire in pečejo prekmursko gibanico. Ponujajo oglede kmetije, degustacije in prodajo lokalnih izdelkov.",
    category: "shop",
    destinationId: "murska-sobota",
    destinationName: "Murska Sobota",
    address: "Bogojina 35, 9226 Bogojina",
    phone: "+386 2 533 4400",
    email: "info@prekmurska-kmetija.si",
    website: "https://www.prekmurska-kmetija.si",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1576181256399-834e3b3a49bf?w=1200&h=800&fit=crop&q=80",
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&h=800&fit=crop&q=80",
    ]),
    plan: "premium",
    featured: true,
    verified: true,
    rating: 4.6,
    reviewCount: 312,
    priceRange: "€€",
    openingHours: "Pon-Sob 9:00-19:00",
    specialties: JSON.stringify([
      "Bučno olje",
      "Prekmurska gibanica",
      "Degustacije",
      "Družinska tradicija",
    ]),
    ownerEmail: "info@prekmurska-kmetija.si",
  },
  // === DOLENJSKA ===
  {
    name: "Hotel Otočec",
    slug: "hotel-otocec",
    description: "Edini slovenski grad na otoku reke — luksuzen hotel z golfom in wellnessom.",
    longDescription:
      "Hotel Otočec Grad je edini slovenski grad na otoku reke Krke, preurejen v luksuzen 4* hotel. Ponuja 18-luknjično golf igrišče, wellness center, restavracijo z vrhunsko kuhinjo in romantično vzdušje za pare.",
    category: "hotel",
    destinationId: "otocec",
    destinationName: "Otočec",
    address: "Otočec 1, 8222 Otočec",
    phone: "+386 7 308 4000",
    email: "info@hotel-otocec.si",
    website: "https://www.otocec.si",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200&h=800&fit=crop&q=80",
      "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=1200&h=800&fit=crop&q=80",
    ]),
    plan: "enterprise",
    featured: true,
    verified: true,
    rating: 4.7,
    reviewCount: 423,
    priceRange: "€€€",
    openingHours: "24/7 recepcija",
    specialties: JSON.stringify([
      "Grad na otoku",
      "Golf",
      "Wellness",
      "Romantično",
    ]),
    ownerEmail: "info@hotel-otocec.si",
  },
  {
    name: "Vinska klet Cviček",
    slug: "vinska-klet-cvicek",
    description: "Dolenjska vinska klet specializirana za cviček in lokalne sorte.",
    longDescription:
      "Vinska klet Cviček je v Novem mestu specializirana za pridelavo cvička — tradicionalnega dolenjskega rdečega vina z zaščiteno označbo. Ponujajo degustacije, oglede kleti in prodajo vrhunskih dolenjskih vin.",
    category: "shop",
    destinationId: "novo-mesto",
    destinationName: "Novo mesto",
    address: "Kandijska cesta 50, 8000 Novo mesto",
    phone: "+386 7 337 8900",
    email: "info@klet-cvicek.si",
    website: "https://www.klet-cvicek.si",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=1200&h=800&fit=crop&q=80",
      "https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=1200&h=800&fit=crop&q=80",
    ]),
    plan: "premium",
    featured: false,
    verified: true,
    rating: 4.6,
    reviewCount: 234,
    priceRange: "€",
    openingHours: "Pon-Pet 9:00-19:00, Sob 9:00-14:00",
    specialties: JSON.stringify([
      "Cviček",
      "Dolenjska vina",
      "Degustacije",
      "Zaščitena označba",
    ]),
    ownerEmail: "info@klet-cvicek.si",
  },
  // === BELA KRAJINA ===
  {
    name: "Belokranjska hiša",
    slug: "belokranjska-hisa",
    description: "Tradicionalna belokranjska restavracija s pisanicami in Kolpo v ozadju.",
    longDescription:
      "Belokranjska hiša je tradicionalna restavracija v Črnomlju, ki ohranja belokranjsko kulinarično in etnografsko tradicijo. Ponujajo belokranjsko pogačo, koline, domača vina in pivo. V poletnih mesecih organizirajo izlete na Kolpo.",
    category: "restaurant",
    destinationId: "crnomelj",
    destinationName: "Črnomelj",
    address: "Glavni trg 8, 8340 Črnomelj",
    phone: "+386 7 305 2200",
    email: "info@belokranjska-hisa.si",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1200&h=800&fit=crop&q=80",
    ]),
    plan: "free",
    featured: false,
    verified: true,
    rating: 4.5,
    reviewCount: 167,
    priceRange: "€€",
    openingHours: "Pon-Ned 11:00-22:00",
    specialties: JSON.stringify([
      "Belokranjska pogača",
      "Koline",
      "Lokalna vina",
      "Etnografska tradicija",
    ]),
  },
];

// ----------------------------------------------------------------------------
// 20 NOVIH PRODUCTS — kategorije: food(5) + wine(4) + honey(3) + oil(3) + craft(3) + souvenir(2)
// ----------------------------------------------------------------------------
const newProducts = [
  // === FOOD (5) ===
  {
    name: "Idrijski žlikrofi (zamrznjeni, 1kg)",
    slug: "idrijski-zlikrofi-zamrznjeni-1kg",
    description:
      "Tradicionalni idrijski žlikrofi z krompirjevo oblogo, zaščiteni z oznako tradicionalnega ugleda.",
    longDescription:
      "Idrijski žlikrofi so slovenska različica raviolijev — mali dvignjeni žepki iz testa s krompirjevo oblogo, zelišči in čebulo. Zaščiteni z oznako tradicionalnega ugleda od leta 2002. Pakirano zamrznjeno, 1kg (~50 kosov).",
    category: "food",
    destinationId: "ljubljana",
    destinationName: "Ljubljana",
    price: 14.9,
    compareAtPrice: 17.9,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1473093226795-af9932fe5856?w=1200&h=800&fit=crop&q=80",
    ]),
    stock: 40,
    weight: 1050,
    organic: false,
    handmade: true,
    local: true,
    vegan: false,
    shippingFree: false,
    shipsEurope: true,
    shipsWorldwide: false,
    plan: "premium",
    featured: true,
    verified: true,
    rating: 4.8,
    reviewCount: 156,
    sellerName: "Idrijska okusca",
    sellerEmail: "info@idrijska-okusca.si",
    sellerWebsite: "https://www.idrijska-okusca.si",
  },
  {
    name: "Ajdovi žganci 1kg",
    slug: "ajdovi-zganci-1kg",
    description:
      "Tradicionalni ajdovi žganci iz Koroške — polnozrnata ajdova kaša z drobtinami.",
    longDescription:
      "Ajdovi žganci so tradicionalna slovenska jed iz ajdove moke in drobtin, ki se pogosto postrežejo s kislim mlekom ali ocvirki. Naša različica prihaja iz koroških kmetij, kjer ajdo pridelujejo ekološko. Pakirano 1kg, brez glutena.",
    category: "food",
    destinationId: "dravograd",
    destinationName: "Dravograd",
    price: 5.9,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1568254183919-78a4f43a2877?w=1200&h=800&fit=crop&q=80",
    ]),
    stock: 75,
    weight: 1050,
    organic: true,
    handmade: false,
    local: true,
    vegan: true,
    shippingFree: true,
    shipsEurope: true,
    shipsWorldwide: true,
    plan: "free",
    featured: false,
    verified: true,
    rating: 4.7,
    reviewCount: 89,
    sellerName: "Kmetija Pohorje",
    sellerEmail: "info@kmetija-pohorje.si",
  },
  {
    name: "Tolminski sir 1kg",
    slug: "tolminski-sir-1kg",
    description:
      "Trdi sir iz Tolminskega, zoren najmanj 6 mesecev na pašnikih Soške doline.",
    longDescription:
      "Tolminski sir je trdi sir iz kravjega mleka, pridelanega na pašnikih Soške doline. Zoren 6-12 mesecev v naravnih jamah. Polnega, pikantnega okusa z orehovim pridihom. Pakirano 1kg, brez konzervansov.",
    category: "food",
    destinationId: "kobarid",
    destinationName: "Kobarid",
    price: 24.9,
    compareAtPrice: 28.0,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=1200&h=800&fit=crop&q=80",
    ]),
    stock: 25,
    weight: 1050,
    organic: false,
    handmade: true,
    local: true,
    vegan: false,
    shippingFree: true,
    shipsEurope: true,
    shipsWorldwide: false,
    plan: "premium",
    featured: true,
    verified: true,
    rating: 4.8,
    reviewCount: 134,
    sellerName: "Sirarna Tolmin",
    sellerEmail: "info@sirarna-tolmin.si",
    sellerWebsite: "https://www.sirarna-tolmin.si",
  },
  {
    name: "Orehova potica 1kg",
    slug: "orehova-potica-1kg",
    description:
      "Tradicionalna slovenska potica z orehi in rozinami, pečena v lončarici.",
    longDescription:
      "Orehova potica je praznični slovenski zavitek, ki ga pečemo za vsako posebno priložnost. Naša različica je pečena po družinskem receptu z ekološkimi orehi in rozinami. Pakirano 1kg, primerno za 10-12 oseb.",
    category: "food",
    destinationId: "celje",
    destinationName: "Celje",
    price: 18.0,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=1200&h=800&fit=crop&q=80",
    ]),
    stock: 20,
    weight: 1050,
    organic: false,
    handmade: true,
    local: true,
    vegan: false,
    shippingFree: false,
    shipsEurope: false,
    shipsWorldwide: false,
    plan: "free",
    featured: false,
    verified: true,
    rating: 4.9,
    reviewCount: 78,
    sellerName: "Pekarna Savinja",
    sellerEmail: "info@pekarna-savinja.si",
  },
  {
    name: "Krškopoljski prašič (šunka 500g)",
    slug: "krskopoljski-prasic-sunka-500g",
    description:
      "Šunka iz krškopoljskega prašiča — edine slovenske avtohtone pasme, sušena 6 mesecev.",
    longDescription:
      "Krškopoljski prašič je edina slovenska avtohtona pasma prašičev. Šunka je sušena 6 mesecev na zraku, brez konzervansov. Polnega okusa z nežno sladkim pridihom. Pakirano 500g.",
    category: "food",
    destinationId: "novo-mesto",
    destinationName: "Novo mesto",
    price: 16.5,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1528607929212-2636ec44253e?w=1200&h=800&fit=crop&q=80",
    ]),
    stock: 35,
    weight: 550,
    organic: true,
    handmade: true,
    local: true,
    vegan: false,
    shippingFree: false,
    shipsEurope: true,
    shipsWorldwide: false,
    plan: "premium",
    featured: true,
    verified: true,
    rating: 4.8,
    reviewCount: 112,
    sellerName: "Kmetija Dolenjska",
    sellerEmail: "info@kmetija-dolenjska.si",
    sellerWebsite: "https://www.kmetija-dolenjska.si",
  },
  // === WINE (4) ===
  {
    name: "Modra frankinja 0.75l — Štajerska",
    slug: "modra-frankinja-075l",
    description:
      "Tradicionalno štajersko rdeče vino iz sorte Modra frankinja. Sveže, z malinovo aromo.",
    longDescription:
      "Modra frankinja je avtohtona štajerska sorta, ki daje sveža, sadna vina z aromami malin in višnje. Pridelano v vinogradih Pohorja nad Mariborom. Serverirati pri 14-16°C z belim mesom ali testeninami.",
    category: "wine",
    destinationId: "maribor",
    destinationName: "Maribor",
    price: 12.5,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=1200&h=800&fit=crop&q=80",
    ]),
    stock: 80,
    weight: 1300,
    organic: false,
    handmade: false,
    local: true,
    vegan: true,
    shippingFree: false,
    shipsEurope: true,
    shipsWorldwide: false,
    plan: "premium",
    featured: true,
    verified: true,
    rating: 4.6,
    reviewCount: 167,
    sellerName: "Vinogradništvo Maribor",
    sellerEmail: "info@vinogradnistvo-maribor.si",
    sellerWebsite: "https://www.vinogradnistvo-maribor.si",
  },
  {
    name: "Renski rizling 0.75l — Savinja",
    slug: "renski-rizling-075l",
    description:
      "Klasični savinjski renski rizling z mineralno aromo in dolgim pookusom.",
    longDescription:
      "Renski rizling je kraljica belih vin, pridelan v savinjskih vinogradih. Srednje polno telo, sveža kislina, aromi breskve in citrusov. Serverirati pri 10-12°C z ribami, perutnino ali belim mesom.",
    category: "wine",
    destinationId: "celje",
    destinationName: "Celje",
    price: 13.9,
    compareAtPrice: 16.0,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1566995541428-f2c5bb2cd6c3?w=1200&h=800&fit=crop&q=80",
    ]),
    stock: 95,
    weight: 1300,
    organic: false,
    handmade: false,
    local: true,
    vegan: true,
    shippingFree: false,
    shipsEurope: true,
    shipsWorldwide: false,
    plan: "premium",
    featured: false,
    verified: true,
    rating: 4.7,
    reviewCount: 203,
    sellerName: "Vinogradništvo Savinja",
    sellerEmail: "info@vino-savinja.si",
  },
  {
    name: "Rumeni muškat 0.75l — Haloze",
    slug: "rumeni-muskat-075l",
    description:
      "Sladki rumeni muškat iz halozanskih vinogradov z močno cvetlično aromo.",
    longDescription:
      "Rumeni muškat iz halozanskih vinogradov nad Ptujsko gorco. Intenzivna cvetlična aroma z navzočnostjo rož in citrusov. Sladko, harmonično vino. Serverirati pri 8-10°C kot aperitiv ali s sadnimi sladicami.",
    category: "wine",
    destinationId: "ptuj",
    destinationName: "Ptuj",
    price: 14.5,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1558001373-7b93ee48ffa0?w=1200&h=800&fit=crop&q=80",
    ]),
    stock: 60,
    weight: 1300,
    organic: false,
    handmade: false,
    local: true,
    vegan: true,
    shippingFree: false,
    shipsEurope: true,
    shipsWorldwide: false,
    plan: "free",
    featured: false,
    verified: false,
    rating: 4.5,
    reviewCount: 89,
    sellerName: "Vinogradništvo Haloze",
    sellerEmail: "info@vino-haloze.si",
  },
  {
    name: "Cviček 0.75l — Dolenjska",
    slug: "cvicek-075l",
    description:
      "Tradicionalno dolenjsko vino cviček z zaščiteno označbo porekla. Lahek, svež.",
    longDescription:
      "Cviček je tradicionalno dolenjsko rdeče vino z zaščiteno označbo porekla. Narejen iz mešanice rdečih in belih sort (žlahtna metka, modra frankinja, kraljevina). Nizka vsebnost alkohola (8-10%), svež, kisel, lahek. Serverirati pri 12-14°C z vsakdanjimi jedmi.",
    category: "wine",
    destinationId: "novo-mesto",
    destinationName: "Novo mesto",
    price: 7.9,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1566995541428-f2c5bb2cd6c3?w=1200&h=800&fit=crop&q=80",
    ]),
    stock: 150,
    weight: 1300,
    organic: false,
    handmade: false,
    local: true,
    vegan: true,
    shippingFree: true,
    shipsEurope: true,
    shipsWorldwide: false,
    plan: "free",
    featured: true,
    verified: true,
    rating: 4.5,
    reviewCount: 234,
    sellerName: "Vinska zveza Dolenjska",
    sellerEmail: "info@vinska-zveza-dolenjska.si",
    sellerWebsite: "https://www.cvicek-dolenjska.si",
  },
  // === HONEY (3) ===
  {
    name: "Ajdov med 500g — Koroška",
    slug: "ajdov-med-500g",
    description:
      "Temni, robustni ajdov med iz koroških ajdovih polj. Bogat z minerali.",
    longDescription:
      "Ajdov med je temen, močan med z značilnim pikantnim okusom. Pridelovan v koroških ajdovih poljih, kjer čebele obdelujejo ajdove cvetove. Bogat z železom in magnezijem. Kristalizira hitro v drobne kristale. Pakirano 500g.",
    category: "honey",
    destinationId: "dravograd",
    destinationName: "Dravograd",
    price: 9.9,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=1200&h=800&fit=crop&q=80",
    ]),
    stock: 60,
    weight: 600,
    organic: true,
    handmade: true,
    local: true,
    vegan: false,
    shippingFree: true,
    shipsEurope: true,
    shipsWorldwide: true,
    plan: "premium",
    featured: true,
    verified: true,
    rating: 4.8,
    reviewCount: 178,
    sellerName: "Čebelarstvo Koroška",
    sellerEmail: "info@cebelarstvo-koroska.si",
    sellerWebsite: "https://www.cebelarstvo-koroska.si",
  },
  {
    name: "Gozdni med 1kg — Pohorje",
    slug: "gozdni-med-1kg",
    description:
      "Temni gozdni med iz pohorskih gozdov z medenjaki (mane). Bogat z minerali.",
    longDescription:
      "Gozdni med je med iz medenjaka (mane), ki ga čebele pridobivajo iz listov dreves v pohorskih gozdovih. Temno rjave barve, z globokim, karamelnim okusom. Bogat z minerali in antioksidanti. Pakirano 1kg.",
    category: "honey",
    destinationId: "slovenj-gradec",
    destinationName: "Slovenj Gradec",
    price: 16.5,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=1200&h=800&fit=crop&q=80",
    ]),
    stock: 45,
    weight: 1100,
    organic: true,
    handmade: false,
    local: true,
    vegan: false,
    shippingFree: true,
    shipsEurope: true,
    shipsWorldwide: false,
    plan: "free",
    featured: false,
    verified: true,
    rating: 4.7,
    reviewCount: 124,
    sellerName: "Čebelarstvo Pohorje",
    sellerEmail: "info@cebelarstvo-pohorje.si",
  },
  {
    name: "Akacijev med 500g — Prekmurje",
    slug: "akacijev-med-500g",
    description:
      "Svetli akacijev med iz prekmurskih akacijevih gozdov. Blag, sladek, dolgo tekoč.",
    longDescription:
      "Akacijev med je svetel, bledo rumen med z nežnim, cvetličnim okusom. Pridelovan v prekmurskih akacijevih gozdovih. Zaradi visoke vsebnosti fruktoze dolgo ostane tekoč. Pakirano 500g.",
    category: "honey",
    destinationId: "murska-sobota",
    destinationName: "Murska Sobota",
    price: 8.5,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=1200&h=800&fit=crop&q=80",
    ]),
    stock: 90,
    weight: 600,
    organic: true,
    handmade: false,
    local: true,
    vegan: false,
    shippingFree: false,
    shipsEurope: true,
    shipsWorldwide: true,
    plan: "free",
    featured: false,
    verified: true,
    rating: 4.6,
    reviewCount: 89,
    sellerName: "Čebelarstvo Prekmurje",
    sellerEmail: "info@cebelarstvo-prekmurje.si",
  },
  // === OIL (3) ===
  {
    name: "Laneno olje 250ml — Ljubljana",
    slug: "laneno-olje-250ml",
    description:
      "Hladno stiskano laneno olje bogato z omega-3 maščobnimi kislinami. Zlatno rumene barve.",
    longDescription:
      "Laneno olje je hladno stiskano iz slovenskih lanovih semen. Zlatno rumene barve z značilnim, rahlo travnatim okusom. Izjemno bogato z omega-3 maščobnimi kislinami. Idealno za solate in hladne jedi — ne segrevajte. Pakirano 250ml v temnem steklu.",
    category: "oil",
    destinationId: "ljubljana",
    destinationName: "Ljubljana",
    price: 9.9,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=1200&h=800&fit=crop&q=80",
    ]),
    stock: 50,
    weight: 350,
    organic: true,
    handmade: false,
    local: true,
    vegan: true,
    shippingFree: false,
    shipsEurope: true,
    shipsWorldwide: true,
    plan: "free",
    featured: false,
    verified: true,
    rating: 4.6,
    reviewCount: 67,
    sellerName: "Oljarna Ljubljana",
    sellerEmail: "info@oljarna-ljubljana.si",
  },
  {
    name: "Bučno olje ekstra 250ml — Lendava",
    slug: "bucno-olje-ekstra-250ml",
    description:
      "Premium bučno olje iz lendavskih buč, hladno stiskano v manjših serijah.",
    longDescription:
      "Premium bučno olje iz lendavskih buč (slovensko oljno seme), hladno stiskano v manjših serijah v družinski oljarni. Temno rdeče-rjave barve z intenzivnim orehovim okusom. Pakirano 250ml v temnem steklu. Za solate, juhe in prelive.",
    category: "oil",
    destinationId: "lendava",
    destinationName: "Lendava",
    price: 8.9,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=1200&h=800&fit=crop&q=80",
    ]),
    stock: 70,
    weight: 350,
    organic: true,
    handmade: true,
    local: true,
    vegan: true,
    shippingFree: false,
    shipsEurope: true,
    shipsWorldwide: false,
    plan: "premium",
    featured: true,
    verified: true,
    rating: 4.9,
    reviewCount: 145,
    sellerName: "Oljarna Lendava",
    sellerEmail: "info@oljarna-lendava.si",
    sellerWebsite: "https://www.oljarna-lendava.si",
  },
  {
    name: "Oljčno olje Koper 0.25l — Slovenska Istra",
    slug: "oljno-olje-koper-025l",
    description:
      "Ekstra deviško oljčno olje iz sort Istrska belica, manjši format 250ml.",
    longDescription:
      "Ekstra deviško oljčno olje iz koprskih oljčnikov, pridelano iz sorte Istrska belica. Hladno stiskano, nizka kislost. Srednje intenzivno, s travnato-dišavnim okusom in rahlim poprom v grlu. Pakirano 250ml v temnem steklu.",
    category: "oil",
    destinationId: "piran",
    destinationName: "Piran",
    price: 11.5,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=1200&h=800&fit=crop&q=80",
    ]),
    stock: 55,
    weight: 350,
    organic: true,
    handmade: false,
    local: true,
    vegan: true,
    shippingFree: false,
    shipsEurope: true,
    shipsWorldwide: true,
    plan: "free",
    featured: false,
    verified: true,
    rating: 4.7,
    reviewCount: 92,
    sellerName: "Oljarna Strunjan",
    sellerEmail: "info@oljarna-strunjan.si",
  },
  // === CRAFT (3) ===
  {
    name: "Keramika Slovenj Gradec (set 3 kosi)",
    slug: "keramika-slovenj-gradec-set-3",
    description:
      "Ročno izdelana keramična posoda iz Slovenj Gradca, set 3 kosi.",
    longDescription:
      "Ročno izdelana keramična posoda iz delavnice v Slovenj Gradcu. Set treh kosov — skleda, krožnik in vrč. Vsak kos je edinstven, s tradicionalnim koroškim vzorcem. Žgan pri 1200°C, primerno za vsakodnevno uporabo in pomivalni stroj.",
    category: "craft",
    destinationId: "slovenj-gradec",
    destinationName: "Slovenj Gradec",
    price: 39.0,
    compareAtPrice: 45.0,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=1200&h=800&fit=crop&q=80",
    ]),
    stock: 18,
    weight: 1800,
    organic: false,
    handmade: true,
    local: true,
    vegan: true,
    shippingFree: true,
    shipsEurope: true,
    shipsWorldwide: true,
    plan: "premium",
    featured: true,
    verified: true,
    rating: 4.9,
    reviewCount: 67,
    sellerName: "Keramika Koroška",
    sellerEmail: "info@keramika-koroska.si",
    sellerWebsite: "https://www.keramika-koroska.si",
  },
  {
    name: "Vezena miza (ročno vezena)",
    slug: "vezena-miza-rocno-vezena",
    description:
      "Ročno vezena miza iz celjske delavnice s tradicionalnim savinjskim vzorcem.",
    longDescription:
      "Ročno vezena miza iz celjske delavnice z tradicionalnim savinjskim vzorcem. Izdelana iz 100% lanenega platna z naravno barvanimi nitmi. Mere 140x80 cm, primerna za jedilnico. Vsak kos je unikaten, vezen z roko več kot 30 ur.",
    category: "craft",
    destinationId: "celje",
    destinationName: "Celje",
    price: 49.0,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1493106641515-6b5631de4bb9?w=1200&h=800&fit=crop&q=80",
    ]),
    stock: 12,
    weight: 800,
    organic: true,
    handmade: true,
    local: true,
    vegan: true,
    shippingFree: true,
    shipsEurope: true,
    shipsWorldwide: false,
    plan: "premium",
    featured: false,
    verified: true,
    rating: 4.8,
    reviewCount: 34,
    sellerName: "Vezenje Savinja",
    sellerEmail: "info@vezenje-savinja.si",
  },
  {
    name: "Leseni izdelki (rezilna deska)",
    slug: "leseni-izdelki-rezilna-deska",
    description:
      "Ročno izdelana rezilna deska iz bohinjskega lesa, orešček za nož.",
    longDescription:
      "Ročno izdelana rezilna deska iz bohinjskega javorjevega lesa. Trda, trajna, z naravnim oljem za zaščito. Mere 40x25x3 cm. Vsaka deska je edinstvena zaradi naravne strukture lesa. Idealna za slaščičarstvo, sir ali vsakdanjo uporabo.",
    category: "craft",
    destinationId: "bohinj",
    destinationName: "Bohinj",
    price: 24.0,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1556909212-d5b604d0c90d?w=1200&h=800&fit=crop&q=80",
    ]),
    stock: 30,
    weight: 1500,
    organic: false,
    handmade: true,
    local: true,
    vegan: true,
    shippingFree: false,
    shipsEurope: true,
    shipsWorldwide: true,
    plan: "free",
    featured: false,
    verified: true,
    rating: 4.7,
    reviewCount: 56,
    sellerName: "Lesarna Bohinj",
    sellerEmail: "info@lesarna-bohinj.si",
  },
  // === SOUVENIR (2) ===
  {
    name: "Magnet Slovenija (set 5)",
    slug: "magnet-slovenija-set-5",
    description:
      "Set 5 magnetov z motivi slovenskih mest in znamenitosti.",
    longDescription:
      "Set 5 magnetov z najbolj znanimi slovenskimi motivi: Bled, Ljubljana, Triglav, Piran in Postojnska jama. Izdelani iz kovine s tiskom v visoki resoluciji. Velikost vsakega magneta 7x5 cm. Idealni spomin na obisk Slovenije.",
    category: "souvenir",
    destinationId: "ljubljana",
    destinationName: "Ljubljana",
    price: 12.0,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1513151233558-d860c5398176?w=1200&h=800&fit=crop&q=80",
    ]),
    stock: 200,
    weight: 250,
    organic: false,
    handmade: false,
    local: true,
    vegan: true,
    shippingFree: true,
    shipsEurope: true,
    shipsWorldwide: true,
    plan: "free",
    featured: false,
    verified: false,
    rating: 4.4,
    reviewCount: 234,
    sellerName: "Suvenirnica Ljubljana",
    sellerEmail: "info@suvenirnica-ljubljana.si",
  },
  {
    name: "Tradicionalni okrasek (lipov list)",
    slug: "tradicionalni-okrasek-lipov-list",
    description:
      "Ročno izdelan okrasek v obliki lipovega lista, simbola Slovenije.",
    longDescription:
      "Ročno izdelan okrasek v obliki lipovega lista — simbola Slovenije. Izdelan iz keramike z ročno pobarvanim vzorcem. Velikost 8x6 cm, z luknjo za obešanje. Pakirano v darilni škatli. Idealno darilo za tujce in domoljube.",
    category: "souvenir",
    destinationId: "bled",
    destinationName: "Bled",
    price: 14.5,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1513151233558-d860c5398176?w=1200&h=800&fit=crop&q=80",
    ]),
    stock: 75,
    weight: 200,
    organic: false,
    handmade: true,
    local: true,
    vegan: true,
    shippingFree: false,
    shipsEurope: true,
    shipsWorldwide: true,
    plan: "premium",
    featured: true,
    verified: true,
    rating: 4.7,
    reviewCount: 89,
    sellerName: "Suvenirnica Bled",
    sellerEmail: "info@suvenirnica-bled.si",
    sellerWebsite: "https://www.suvenirnica-bled.si",
  },
];

// ----------------------------------------------------------------------------
// 20 NOVIH EXPERIENCES — kategorije: tour(4) + workshop(3) + tasting(4) + outdoor(4) + cultural(2) + adventure(2) + wellness(1)
// ----------------------------------------------------------------------------
const newExperiences = [
  // === TOUR (4) ===
  {
    name: "Mestni ogled Ljubljana — 2,5 ure",
    slug: "mestni-ogled-ljubljana",
    description:
      "Vodeni ogled starega mesta Ljubljana z lokalnim vodnikom. Prešernov trg, grad, Tromostovje.",
    longDescription:
      "Vodeni ogled Ljubljane z izkušenim lokalnim vodnikom. 2,5-urni sprehod po starem mestnem jedru: Prešernov trg, Tromostovje, Plečnikova tržnica, Ljubljanski grad (z žičnico), Zmajev most in Stari trg. Vključuje vstopnino za grad in žičnico.",
    category: "tour",
    destinationId: "ljubljana",
    destinationName: "Ljubljana",
    pricePerPerson: 35,
    durationHours: 2.5,
    minGroupSize: 1,
    maxGroupSize: 15,
    languages: JSON.stringify(["sl", "en", "de"]),
    meetingPoint: "Prešernov trg, pred Tromostovjem",
    address: "Prešernov trg, 1000 Ljubljana",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=1200&h=800&fit=crop&q=80",
    ]),
    providerName: "Ljubljana Walking Tours",
    providerEmail: "info@ljubljana-walking.si",
    providerPhone: "+386 1 234 5678",
    providerWebsite: "https://www.ljubljana-walking.si",
    plan: "premium",
    featured: true,
    verified: true,
    rating: 4.7,
    reviewCount: 892,
    familyFriendly: true,
    accessibility: true,
    bookingCount: 2341,
  },
  {
    name: "Maribor staro mesto in Stara trta — 2 uri",
    slug: "maribor-staro-mesto-stara-trta",
    description:
      "Vodeni ogled Maribora z obiskom najstarejše trte na svetu in Lent.",
    longDescription:
      "2-urni vodeni ogled Maribora: Glavni trg, Stolnica, Lent (najstarejši del mesta), obisk najstarejše trte na svetu (vpisana v Guinnessovo knjigo rekordov). Vključuje kozarec modre frankinje v vinski kleti Stara trta.",
    category: "tour",
    destinationId: "maribor",
    destinationName: "Maribor",
    pricePerPerson: 28,
    durationHours: 2,
    minGroupSize: 2,
    maxGroupSize: 12,
    languages: JSON.stringify(["sl", "en", "de"]),
    meetingPoint: "Glavni trg, pred sodno palačo",
    address: "Glavni trg, 2000 Maribor",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=1200&h=800&fit=crop&q=80",
    ]),
    providerName: "Maribor Tours",
    providerEmail: "info@maribor-tours.si",
    providerPhone: "+386 2 234 5678",
    providerWebsite: "https://www.maribor-tours.si",
    plan: "premium",
    featured: false,
    verified: true,
    rating: 4.6,
    reviewCount: 234,
    familyFriendly: true,
    accessibility: true,
    bookingCount: 567,
  },
  {
    name: "Ptuj zgodovinski ogled — 2 uri",
    slug: "ptuj-zgodovinski-ogled",
    description:
      "Vodeni ogled Ptuja — najstarejšega mesta v Sloveniji z rimskimi izkopaninami.",
    longDescription:
      "2-urni zgodovinski ogled Ptuja, najstarejšega mesta v Sloveniji. Rimski Poetovio, srednjeveški Stari trg, Ptujski grad z muzejem, mestna cerkev. Vključuje vstopnino za Ptujski grad in pokrajinski muzej.",
    category: "tour",
    destinationId: "ptuj",
    destinationName: "Ptuj",
    pricePerPerson: 25,
    durationHours: 2,
    minGroupSize: 1,
    maxGroupSize: 10,
    languages: JSON.stringify(["sl", "en"]),
    meetingPoint: "Stari trg, pred mestno hišo",
    address: "Stari trg, 2250 Ptuj",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=1200&h=800&fit=crop&q=80",
    ]),
    providerName: "Ptuj Heritage",
    providerEmail: "info@ptuj-heritage.si",
    providerPhone: "+386 2 787 1234",
    providerWebsite: "https://www.ptuj-heritage.si",
    plan: "free",
    featured: false,
    verified: true,
    rating: 4.5,
    reviewCount: 123,
    familyFriendly: true,
    accessibility: true,
    bookingCount: 234,
  },
  {
    name: "Celje — grad Celjskih grofov — 2 uri",
    slug: "celje-grad-grofov",
    description:
      "Vodeni ogled Starega gradu Celje z zgodovino najvplivnejšega slovenskega plemiškega rodu.",
    longDescription:
      "2-urni vodeni ogled Starega gradu Celje, nekdanje prestolnice Celjskih grofov. Spoznajte zgodovino najvplivnejšega slovenskega plemiškega rodu, obiščite muzej, obrambni stol in razgledišče. Vključuje vstopnino za grad.",
    category: "tour",
    destinationId: "celje",
    destinationName: "Celje",
    pricePerPerson: 22,
    durationHours: 2,
    minGroupSize: 2,
    maxGroupSize: 15,
    languages: JSON.stringify(["sl", "en", "de"]),
    meetingPoint: "Cesta na grad, pred vzpenjačo",
    address: "Cesta na grad 9, 3000 Celje",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=1200&h=800&fit=crop&q=80",
    ]),
    providerName: "Celje Tours",
    providerEmail: "info@celje-tours.si",
    providerPhone: "+386 3 425 5678",
    providerWebsite: "https://www.celje-tours.si",
    plan: "free",
    featured: false,
    verified: true,
    rating: 4.4,
    reviewCount: 89,
    familyFriendly: true,
    accessibility: false,
    bookingCount: 156,
  },
  // === WORKSHOP (3) ===
  {
    name: "Delavnica keramike — Slovenj Gradec",
    slug: "delavnica-keramike",
    description:
      "3-urna delavnica izdelave keramike z lokalnim mojstrom. Odnesete svoj izdelek.",
    longDescription:
      "3-urna delavnica izdelave keramike v delavnici v Slovenj Gradcu. Pod vodstvom izkušenega mojstra boste izdelali svoj keramični izdelek — skledo, vrč ali okras. Vsi materiali vključeni. Izdelek bo žgan in poslan po pošti v 2 tednih.",
    category: "workshop",
    destinationId: "slovenj-gradec",
    destinationName: "Slovenj Gradec",
    pricePerPerson: 45,
    durationHours: 3,
    minGroupSize: 2,
    maxGroupSize: 8,
    languages: JSON.stringify(["sl", "en"]),
    meetingPoint: "Keramična delavnica, Stari trg",
    address: "Stari trg 12, 2380 Slovenj Gradec",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=1200&h=800&fit=crop&q=80",
    ]),
    providerName: "Keramika Koroška",
    providerEmail: "info@keramika-koroska.si",
    providerPhone: "+386 2 881 3344",
    providerWebsite: "https://www.keramika-koroska.si",
    plan: "premium",
    featured: true,
    verified: true,
    rating: 4.8,
    reviewCount: 67,
    familyFriendly: true,
    accessibility: true,
    bookingCount: 134,
  },
  {
    name: "Delavnica peke kruha — Prekmurje",
    slug: "delavnica-peke-kruha",
    description:
      "3-urna delavnica peke tradicionalnega prekmurskega kruha v krušni peči.",
    longDescription:
      "3-urna delavnica peke tradicionalnega prekmurskega kruha v družinski kmetiji. Spoznajte postopek priprave testa z naravnim kvasom, oblikovanja in peke v tradicionalni krušni peči. Vsak udeleženec odnese še topli kruh domov.",
    category: "workshop",
    destinationId: "murska-sobota",
    destinationName: "Murska Sobota",
    pricePerPerson: 38,
    durationHours: 3,
    minGroupSize: 2,
    maxGroupSize: 10,
    languages: JSON.stringify(["sl", "en", "hu"]),
    meetingPoint: "Prekmurska kmetija, Bogojina",
    address: "Bogojina 35, 9226 Bogojina",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=1200&h=800&fit=crop&q=80",
    ]),
    providerName: "Prekmurska kuhinja",
    providerEmail: "info@prekmurska-kuhinja.si",
    providerPhone: "+386 2 533 4400",
    plan: "free",
    featured: false,
    verified: true,
    rating: 4.7,
    reviewCount: 89,
    familyFriendly: true,
    accessibility: true,
    bookingCount: 167,
  },
  {
    name: "Delavnica vina — Maribor",
    slug: "delavnica-vina-maribor",
    description:
      "3-urna delavnica spoznavanja vina z degustacijo 8 štajerskih vin in sirev.",
    longDescription:
      "3-urna delavnica vina v Mariboru z licenciranim sommelierjem. Spoznajte štajerske sorte, postopek pridelave, pravila degustacije. Degustacija 8 vin (4 bela, 4 rdeča) s siremi in pršutom. Vsak udeleženec prejme certifikat.",
    category: "workshop",
    destinationId: "maribor",
    destinationName: "Maribor",
    pricePerPerson: 55,
    durationHours: 3,
    minGroupSize: 2,
    maxGroupSize: 12,
    languages: JSON.stringify(["sl", "en", "de"]),
    meetingPoint: "Vinska šola Maribor, Lent",
    address: "Vojašniška 12, 2000 Maribor",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=1200&h=800&fit=crop&q=80",
    ]),
    providerName: "Maribor Wine School",
    providerEmail: "info@vina-maribor.si",
    providerPhone: "+386 2 234 9100",
    providerWebsite: "https://www.vina-maribor.si",
    plan: "premium",
    featured: true,
    verified: true,
    rating: 4.8,
    reviewCount: 156,
    familyFriendly: false,
    accessibility: true,
    bookingCount: 312,
  },
  // === TASTING (4) ===
  {
    name: "Degustacija vina Maribor — 2 uri",
    slug: "degustacija-vina-maribor",
    description:
      "Degustacija 6 štajerskih vin z lokalnimi sirevi v vinski kleti ob Stari trti.",
    longDescription:
      "2-urna degustacija vina v vinski kleti ob najstarejši trti na svetu. 6 štajerskih vin (modra frankinja, rumeni muškat, renski rizling...) s tradicionalnimi štajerskimi sirevi in pršutom. Vodi izkušeni sommelier v slovenščini ali angleščini.",
    category: "tasting",
    destinationId: "maribor",
    destinationName: "Maribor",
    pricePerPerson: 35,
    durationHours: 2,
    minGroupSize: 1,
    maxGroupSize: 12,
    languages: JSON.stringify(["sl", "en", "de"]),
    meetingPoint: "Vinska klet Stara trta, Lent",
    address: "Vojašniška 8, 2000 Maribor",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=1200&h=800&fit=crop&q=80",
    ]),
    providerName: "Maribor Wine Tours",
    providerEmail: "info@maribor-wine.si",
    providerPhone: "+386 2 251 3000",
    providerWebsite: "https://www.maribor-wine.si",
    plan: "premium",
    featured: false,
    verified: true,
    rating: 4.7,
    reviewCount: 234,
    familyFriendly: false,
    accessibility: true,
    bookingCount: 567,
  },
  {
    name: "Degustacija sira Bohinj — 1,5 ure",
    slug: "degustacija-sira-bohinj",
    description:
      "Degustacija 8 bohinjskih in alpskih sirev z lokalnim vinom in kruhom.",
    longDescription:
      "1,5-urna degustacija v sirarni Bohinj. 8 različnih sirev: sveži, zreli, alpski, z zelišči. Vsak sir je predstavljen s svojo zgodovino in postopkom izdelave. Postreženo z lokalnim vinom in domačim kruhom. Pogled na Bohinjsko jezero.",
    category: "tasting",
    destinationId: "bohinj",
    destinationName: "Bohinj",
    pricePerPerson: 28,
    durationHours: 1.5,
    minGroupSize: 2,
    maxGroupSize: 10,
    languages: JSON.stringify(["sl", "en"]),
    meetingPoint: "Sirarna Bohinj, Srednja vas",
    address: "Srednja vas 32, 4267 Bohinjsko jezero",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=1200&h=800&fit=crop&q=80",
    ]),
    providerName: "Sirarna Bohinj",
    providerEmail: "info@sirarna-bohinj.si",
    providerPhone: "+386 4 572 3300",
    plan: "free",
    featured: false,
    verified: true,
    rating: 4.7,
    reviewCount: 145,
    familyFriendly: true,
    accessibility: true,
    bookingCount: 234,
  },
  {
    name: "Degustacija medu Dolenjska — 1,5 ure",
    slug: "degustacija-medu-dolenjska",
    description:
      "Degustacija 7 slovenskih medov z lokalnim čebelarjem v Novem mestu.",
    longDescription:
      "1,5-urna degustacija 7 slovenskih medov: akacijev, lipov, gozdni, ajdov, smrekov, kostanjev, cvetlični. Vsak med je predstavljen z zgodovino, postopkom pridelave in zdravilnimi učinki. Postreženo z domačim kruhom in maslom.",
    category: "tasting",
    destinationId: "novo-mesto",
    destinationName: "Novo mesto",
    pricePerPerson: 22,
    durationHours: 1.5,
    minGroupSize: 1,
    maxGroupSize: 8,
    languages: JSON.stringify(["sl", "en"]),
    meetingPoint: "Čebelarstvo Dolenjska, Kandijska cesta",
    address: "Kandijska cesta 50, 8000 Novo mesto",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=1200&h=800&fit=crop&q=80",
    ]),
    providerName: "Čebelarstvo Dolenjska",
    providerEmail: "info@cebelarstvo-dolenjska.si",
    providerPhone: "+386 7 337 8900",
    plan: "free",
    featured: false,
    verified: false,
    rating: 4.6,
    reviewCount: 67,
    familyFriendly: true,
    accessibility: true,
    bookingCount: 89,
  },
  {
    name: "Degustacija olja Piran — 2 uri",
    slug: "degustacija-olja-piran",
    description:
      "Degustacija 5 istrskih oljčnih olj z morskimi sadeži v Strunjanu.",
    longDescription:
      "2-urna degustacija oljčnih olj v oljarni Strunjan ob obali. 5 ekstra deviških oljčnih olj različnih sort (Istrska belica, Leccino, Frantoio). Spoznajte postopek pridelave, degustacija s svežo ribo, morskimi sadeži in domačim kruhom.",
    category: "tasting",
    destinationId: "piran",
    destinationName: "Piran",
    pricePerPerson: 32,
    durationHours: 2,
    minGroupSize: 2,
    maxGroupSize: 10,
    languages: JSON.stringify(["sl", "en", "it"]),
    meetingPoint: "Oljarna Strunjan, Strunjan 32",
    address: "Strunjan 32, 6320 Portorož",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=1200&h=800&fit=crop&q=80",
    ]),
    providerName: "Oljarna Strunjan",
    providerEmail: "info@oljarna-strunjan.si",
    providerPhone: "+386 5 672 2200",
    providerWebsite: "https://www.oljarna-strunjan.si",
    plan: "premium",
    featured: true,
    verified: true,
    rating: 4.8,
    reviewCount: 178,
    familyFriendly: true,
    accessibility: true,
    bookingCount: 234,
  },
  // === OUTDOOR (4) ===
  {
    name: "Pohod na Mangart — 8 ur",
    slug: "pohod-na-mangart",
    description:
      "Celodnevni vodeni pohod na Mangart (2679m), tretji najvišji vrh Slovenije.",
    longDescription:
      "Celodnevni vodeni pohod na Mangart (2679 m) preko Mangartskega sedla. 8 ur, zahtevna pot. Vključuje prevoz do izhodišča, vodnika UIAGM, opremo (klopi, jeklenice) in malico. Pogledi na Julijce, Avstrijo in Italijo z vrha.",
    category: "outdoor",
    destinationId: "soca",
    destinationName: "Reka Soča",
    pricePerPerson: 65,
    durationHours: 8,
    minGroupSize: 2,
    maxGroupSize: 6,
    languages: JSON.stringify(["sl", "en", "de"]),
    meetingPoint: "Mangartska cesta, parkirišče pod Mangartom",
    address: "Mangartska cesta, 5231 Predel",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=1200&h=800&fit=crop&q=80",
    ]),
    providerName: "Soča Mountain Guides",
    providerEmail: "info@soca-guides.si",
    providerPhone: "+386 5 389 6300",
    providerWebsite: "https://www.soca-guides.si",
    plan: "premium",
    featured: false,
    verified: true,
    rating: 4.9,
    reviewCount: 178,
    familyFriendly: false,
    accessibility: false,
    bookingCount: 234,
  },
  {
    name: "Kolesarjenje ob Dravi — 4 ure",
    slug: "kolesarjenje-ob-dravi",
    description:
      "Voden kolesarski ogled ob Dravi od Maribora do Ptuj. Najem kolesa vključen.",
    longDescription:
      "4-urna vodena kolesarska tura ob Dravi od Maribora do Ptuja (35 km). Kolesarska pot Drava je ena najlepših v Sloveniji, ob reki skozi vinograde in vasice. Vključuje najem kolesa, čelada, vodnik in malico v lokalni gostilni v Ptuju.",
    category: "outdoor",
    destinationId: "maribor",
    destinationName: "Maribor",
    pricePerPerson: 35,
    durationHours: 4,
    minGroupSize: 2,
    maxGroupSize: 10,
    languages: JSON.stringify(["sl", "en", "de"]),
    meetingPoint: "Maribor, Lent (ob Dravi)",
    address: "Lent, 2000 Maribor",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1530841379378-3c06a9c2b1c0?w=1200&h=800&fit=crop&q=80",
    ]),
    providerName: "Drava Cycling",
    providerEmail: "info@drava-cycling.si",
    providerPhone: "+386 2 234 5600",
    providerWebsite: "https://www.drava-cycling.si",
    plan: "free",
    featured: true,
    verified: true,
    rating: 4.7,
    reviewCount: 234,
    familyFriendly: true,
    accessibility: true,
    bookingCount: 456,
  },
  {
    name: "Jahanje v Kobarid — 2 uri",
    slug: "jahanje-v-kobarid",
    description:
      "2-urna jahališka izkušnja v Kobaridu z lokalnimi konji in izkušenim inštruktorjem.",
    longDescription:
      "2-urna jahališka izkušnja v jahališču ob Soči blizu Kobarida. Primerno za začetnike in izkušene. Vključuje uvodno lekcijo, jahanje v jahališču in krajši izlet v naravo. Čelada in oprema vključeni.",
    category: "outdoor",
    destinationId: "kobarid",
    destinationName: "Kobarid",
    pricePerPerson: 45,
    durationHours: 2,
    minGroupSize: 1,
    maxGroupSize: 4,
    languages: JSON.stringify(["sl", "en", "it"]),
    meetingPoint: "Jahališče Kobarid, Drežnica",
    address: "Drežnica 12, 5223 Kobarid",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1551986782-d0169b3f8fa7?w=1200&h=800&fit=crop&q=80",
    ]),
    providerName: "Kobarid Riding Club",
    providerEmail: "info@kobarid-riding.si",
    providerPhone: "+386 5 389 1234",
    plan: "free",
    featured: false,
    verified: true,
    rating: 4.7,
    reviewCount: 89,
    familyFriendly: true,
    accessibility: false,
    bookingCount: 134,
  },
  {
    name: "Ribolov na Soči — 6 ur",
    slug: "ribolov-na-soci",
    description:
      "Vodena ribiška izkušnja na Soči z lokalnim vodičem. Soška postrv in glavatica.",
    longDescription:
      "6-urna vodena ribiška izkušnja na Soči s fly fishing tehniko. Lov soške postrvi in glavatice v najlepših odsekih reke. Vključuje najem opreme (ribiška palica, muhe), dovoljenje, vodnika in malico. Dovoljen za ribiče z osnovnim znanjem.",
    category: "outdoor",
    destinationId: "soca",
    destinationName: "Reka Soča",
    pricePerPerson: 80,
    durationHours: 6,
    minGroupSize: 1,
    maxGroupSize: 4,
    languages: JSON.stringify(["sl", "en", "de"]),
    meetingPoint: "Bovec center, pred informacijskim centrom",
    address: "Trg golobarskih žrtev 16, 5230 Bovec",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=1200&h=800&fit=crop&q=80",
    ]),
    providerName: "Soča Fly Fishing",
    providerEmail: "info@soca-flyfishing.si",
    providerPhone: "+386 5 389 6300",
    providerWebsite: "https://www.soca-flyfishing.si",
    plan: "premium",
    featured: true,
    verified: true,
    rating: 4.9,
    reviewCount: 123,
    familyFriendly: false,
    accessibility: false,
    bookingCount: 89,
  },
  // === CULTURAL (2) ===
  {
    name: "Muzej novejše zgodovine Ljubljana — 2 uri",
    slug: "muzej-novejse-zgodovine-ljubljana",
    description:
      "Vodeni ogled Muzeja novejše zgodovine Slovenije v Ljubljani.",
    longDescription:
      "2-urni vodeni ogled Muzeja novejše zgodovine v Ljubljani. Spoznajte slovensko zgodovino od 19. stoletja do danes — prva svetovna vojna, Kraljevina SHS, druga svetovna vojna, socialistična doba, osamosvojitev. Vključuje vstopnino.",
    category: "cultural",
    destinationId: "ljubljana",
    destinationName: "Ljubljana",
    pricePerPerson: 18,
    durationHours: 2,
    minGroupSize: 1,
    maxGroupSize: 20,
    languages: JSON.stringify(["sl", "en", "de"]),
    meetingPoint: "Muzej novejše zgodovine, Celovška cesta",
    address: "Celovška cesta 23, 1000 Ljubljana",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1567361808960-dec9cb578182?w=1200&h=800&fit=crop&q=80",
    ]),
    providerName: "Ljubljana Museums",
    providerEmail: "info@ljubljana-museums.si",
    providerPhone: "+386 1 234 5678",
    plan: "free",
    featured: false,
    verified: true,
    rating: 4.5,
    reviewCount: 89,
    familyFriendly: true,
    accessibility: true,
    bookingCount: 156,
  },
  {
    name: "Ptujski grad in muzej — 2,5 ure",
    slug: "ptujski-grad-in-muzej",
    description:
      "Vodeni ogled Ptujskega gradu s pokrajinskim muzejem in razstavo tradicij.",
    longDescription:
      "2,5-urni vodeni ogled Ptujskega gradu na hribu nad mestom. Grad hrani Pokrajinski muzej z bogatimi zbirkami: rimski in srednjeveški nalazi, plemiške portrete, tradicionalne noše, kurentove maske. Vključuje vstopnino.",
    category: "cultural",
    destinationId: "ptuj",
    destinationName: "Ptuj",
    pricePerPerson: 20,
    durationHours: 2.5,
    minGroupSize: 2,
    maxGroupSize: 15,
    languages: JSON.stringify(["sl", "en"]),
    meetingPoint: "Ptujski grad, vhod",
    address: "Grajska cesta 1, 2250 Ptuj",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=1200&h=800&fit=crop&q=80",
    ]),
    providerName: "Ptuj Museum",
    providerEmail: "info@ptuj-museum.si",
    providerPhone: "+386 2 748 0360",
    providerWebsite: "https://www.ptuj-museum.si",
    plan: "free",
    featured: false,
    verified: true,
    rating: 4.6,
    reviewCount: 78,
    familyFriendly: true,
    accessibility: false,
    bookingCount: 134,
  },
  // === ADVENTURE (2) ===
  {
    name: "Jadralno padalstvo Tolmin — 3 ure",
    slug: "jadralno-padalstvo-tolmin",
    description:
      "Tandem jadralno padalstvo nad Tolminom s pogledom na Sočo in Julijce.",
    longDescription:
      "Tandem jadralno padalstvo iz vzletišča nad Tolminom. 15-20 min leta s poklicnim pilotom. Pogled na Sočo, Julijce in Triglav. Primerno za vse od 16 do 80 let. Vključuje opremo, prevoz do vzletišča in video spomin.",
    category: "adventure",
    destinationId: "soca",
    destinationName: "Reka Soča",
    pricePerPerson: 120,
    durationHours: 3,
    minGroupSize: 1,
    maxGroupSize: 2,
    languages: JSON.stringify(["sl", "en", "de"]),
    meetingPoint: "Tolmin center, pred cerkvijo",
    address: "Trg padlih borcev 1, 5220 Tolmin",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1521673252667-e05da380b252?w=1200&h=800&fit=crop&q=80",
    ]),
    providerName: "Tolmin Paragliding",
    providerEmail: "info@tolmin-paragliding.si",
    providerPhone: "+386 5 389 6300",
    providerWebsite: "https://www.tolmin-paragliding.si",
    plan: "premium",
    featured: true,
    verified: true,
    rating: 4.9,
    reviewCount: 234,
    familyFriendly: false,
    accessibility: false,
    bookingCount: 178,
  },
  {
    name: "Zip-line Učja — 4 ure",
    slug: "zip-line-ucja",
    description:
      "Adrenalinski zip-line čez dolino Učja z najdaljšo progo 700 metrov.",
    longDescription:
      "4-urna adrenalinska izkušnja zip-line v dolini Učja ob italijanski meji. 7 prog, najdaljša 700 metrov, hitrost do 80 km/h. Let nad gozdovi in reko z izkušenimi vodniki. Vključuje opremo in prevoz.",
    category: "adventure",
    destinationId: "soca",
    destinationName: "Reka Soča",
    pricePerPerson: 55,
    durationHours: 4,
    minGroupSize: 1,
    maxGroupSize: 8,
    languages: JSON.stringify(["sl", "en", "de", "it"]),
    meetingPoint: "Učja dolina, parkirišče",
    address: "Učja 5, 5233 Kobarid",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1521673252667-e05da380b252?w=1200&h=800&fit=crop&q=80",
    ]),
    providerName: "Učja Zip-line",
    providerEmail: "info@ucja-zipline.si",
    providerPhone: "+386 5 389 6300",
    providerWebsite: "https://www.ucja-zipline.si",
    plan: "premium",
    featured: false,
    verified: true,
    rating: 4.8,
    reviewCount: 312,
    familyFriendly: true,
    accessibility: false,
    bookingCount: 423,
  },
  // === WELLNESS (1) ===
  {
    name: "Sauna ritual Terme Olimia — 3 ure",
    slug: "sauna-ritual-terme-olimia",
    description:
      "3-urni sauna ritual v Sauna Village Terme Olimia z vodnim vodnikom.",
    longDescription:
      "3-urni sauna ritual v Sauna Village Terme Olimia — največjem kompleksu savn v Sloveniji. 15 različnih savn (finska, rimska, turška, infrared), obredni vstop s premazi in eternimi olji. Vključuje vstopnico, brisačo in zeliščni čaj.",
    category: "wellness",
    destinationId: "rogaska",
    destinationName: "Rogaška Slatina",
    pricePerPerson: 75,
    durationHours: 3,
    minGroupSize: 1,
    maxGroupSize: 6,
    languages: JSON.stringify(["sl", "en", "de"]),
    meetingPoint: "Terme Olimia, recepcija Sauna Village",
    address: "Zdraviliška cesta 24, 3254 Podčetrtek",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1200&h=800&fit=crop&q=80",
    ]),
    providerName: "Terme Olimia",
    providerEmail: "info@terme-olimia.si",
    providerPhone: "+386 3 829 7000",
    providerWebsite: "https://www.terme-olimia.com",
    plan: "premium",
    featured: true,
    verified: true,
    rating: 4.8,
    reviewCount: 234,
    familyFriendly: false,
    accessibility: true,
    bookingCount: 456,
  },
];

// ============================================================================
// MAIN — preveri po slug, dodaj le nove
// ============================================================================
async function main() {
  console.log("🌱 Seed-expand: dodajanje novih listings, products, experiences");
  console.log("   (preverja po slug, ne briše obstoječih)\n");

  // ---- LISTINGS ----
  console.log("📍 Listings...");
  let lAdded = 0;
  let lSkipped = 0;
  for (const listing of newListings) {
    const existing = await db.listing.findUnique({
      where: { slug: listing.slug },
    });
    if (existing) {
      console.log(`  ⏭️  Skip (exists): ${listing.name}`);
      lSkipped++;
      continue;
    }
    await db.listing.create({
      data: {
        ...listing,
        viewCount: Math.floor(Math.random() * 2000) + 100,
        clickCount: Math.floor(Math.random() * 300) + 10,
      },
    });
    console.log(`  ✅ Added: ${listing.name} [${listing.plan}]`);
    lAdded++;
  }

  // ---- PRODUCTS ----
  console.log("\n🛒 Products...");
  let pAdded = 0;
  let pSkipped = 0;
  for (const product of newProducts) {
    const existing = await db.product.findUnique({
      where: { slug: product.slug },
    });
    if (existing) {
      console.log(`  ⏭️  Skip (exists): ${product.name}`);
      pSkipped++;
      continue;
    }
    await db.product.create({
      data: {
        ...product,
        viewCount: Math.floor(Math.random() * 3000) + 100,
        saleCount: Math.floor(Math.random() * 200) + 10,
      },
    });
    console.log(`  ✅ Added: ${product.name} [${product.category}]`);
    pAdded++;
  }

  // ---- EXPERIENCES ----
  console.log("\n🎯 Experiences...");
  let eAdded = 0;
  let eSkipped = 0;
  for (const experience of newExperiences) {
    const existing = await db.experience.findUnique({
      where: { slug: experience.slug },
    });
    if (existing) {
      console.log(`  ⏭️  Skip (exists): ${experience.name}`);
      eSkipped++;
      continue;
    }
    await db.experience.create({
      data: {
        ...experience,
        viewCount: Math.floor(Math.random() * 4000) + 100,
      },
    });
    console.log(`  ✅ Added: ${experience.name} [${experience.category}]`);
    eAdded++;
  }

  // ---- Sponsored update za nove premium/enterprise listings ----
  console.log("\n💎 Sponsored update...");
  const sResult = await db.listing.updateMany({
    where: {
      plan: { in: ["premium", "enterprise"] },
      sponsored: false,
    },
    data: { sponsored: true, sponsoredUntil: new Date("2026-12-31") },
  });
  console.log(`  ✅ Sponsored: ${sResult.count} novih listings`);

  // ---- Skupne statistike ----
  const lTotal = await db.listing.count();
  const pTotal = await db.product.count();
  const eTotal = await db.experience.count();
  const sTotal = await db.listing.count({ where: { sponsored: true } });

  console.log("\n" + "=".repeat(60));
  console.log("📊 SEED EXPAND — povzetek");
  console.log("=".repeat(60));
  console.log(`Listings:    +${lAdded} novih  (${lSkipped} preskočenih)  →  ${lTotal} skupaj`);
  console.log(`Products:    +${pAdded} novih  (${pSkipped} preskočenih)  →  ${pTotal} skupaj`);
  console.log(`Experiences: +${eAdded} novih  (${eSkipped} preskočenih)  →  ${eTotal} skupaj`);
  console.log(`Sponsored:   ${sTotal} skupaj`);
  console.log("=".repeat(60));
}

main()
  .catch((e) => {
    console.error("❌ Seed error:", e);
    process.exit(1);
  })
  .finally(async () => {
    await db.$disconnect();
  });
