import { db } from "@/lib/db";

// Seed 8 slovenskih izdelkov (tržnica) in 8 izkušenj (experiences)
const products = [
  {
    name: "Bučno olje Prekmurje 500ml",
    slug: "pucno-olje-prekmurje-500ml",
    description: "Hladno stiskano bučno olje iz prekmurskih buč — temno rdeče-rjavo, z orehovim okusom.",
    longDescription: "Tradicionalno prekmursko bučno olje, pridelano iz semen buč sorte 'slovensko oljno seme'. Hladno stiskano, nerafinirano. Bogato z omega-3 in omega-6 maščobnimi kislinami. Idealno za solate, juhe in preliv.",
    category: "oil",
    destinationId: "murska-sobota",
    destinationName: "Murska Sobota",
    price: 12.9,
    compareAtPrice: 15.9,
    images: JSON.stringify(["https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=1200&h=800&fit=crop&q=80"]),
    stock: 50,
    weight: 600,
    organic: true,
    handmade: false,
    shippingFree: false,
    shipsEurope: true,
    shipsWorldwide: false,
    plan: "premium",
    featured: true,
    verified: true,
    rating: 4.9,
    reviewCount: 234,
    sellerName: "Kmetija Koroša",
    sellerEmail: "info@korosa.si",
    sellerWebsite: "https://www.korosa.si",
  },
  {
    name: "Slovenski med — Lipa 1kg",
    slug: "slovenski-med-lipa-1kg",
    description: "Čisti lipov med iz slovenskih gozdov. Zlato-rumen, blagega okusa z mentolnim pridihom.",
    longDescription: "Lipov med je najbolj cenjen slovenski med. Pridelovan v čistih gozdovah Kočevske in Notranjske. Kristalizira v drobne kristale. Odličen za čaj, mleko ali preliv.",
    category: "honey",
    destinationId: "novo-mesto",
    destinationName: "Novo mesto",
    price: 18.5,
    images: JSON.stringify(["https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=1200&h=800&fit=crop&q=80"]),
    stock: 80,
    weight: 1100,
    organic: true,
    handmade: true,
    shippingFree: true,
    shipsEurope: true,
    shipsWorldwide: true,
    plan: "premium",
    featured: true,
    verified: true,
    rating: 4.8,
    reviewCount: 412,
    sellerName: "Čebelarstvo Pohorje",
    sellerEmail: "info@pohorje-med.si",
  },
  {
    name: "Teran 0.75l — Kras",
    slug: "teran-075l-kras",
    description: "Tradicionalno kraško rdeče vino Teran, zaščiteno označbo porekla. Surov, globok okus.",
    longDescription: "Teran je avtohtona sorta rdečega vina kraške regije. Pridelano iz sorte Refošk na rdeči kraški zemlji. Bogato s铁 in polifenoli. Serverirati pri 16-18°C z mesnimi jedmi ali pršutom.",
    category: "wine",
    destinationId: "postojna",
    destinationName: "Postojnska jama",
    price: 14.9,
    images: JSON.stringify(["https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=1200&h=800&fit=crop&q=80"]),
    stock: 120,
    weight: 1300,
    organic: false,
    handmade: false,
    shippingFree: false,
    shipsEurope: true,
    shipsWorldwide: false,
    plan: "premium",
    featured: true,
    verified: true,
    rating: 4.7,
    reviewCount: 187,
    sellerName: "Vinogradništvo Kras",
    sellerEmail: "info@vinokras.si",
  },
  {
    name: "Bohinjski sir 1kg",
    slug: "bohinjski-sir-1kg",
    description: "Tradicionalni bohinjski sir iz Alp. Polnega okusa, zoren najmanj 3 mesece.",
    longDescription: "Bohinjski sir je trdi sir iz kravjega mleka, pridelanega na pašnikih Triglavskega narodnega parka. Zoren 3-6 mesecev. Svetlo rumene barve z majhnimi očmi. Sladko-slana aroma.",
    category: "food",
    destinationId: "bohinj",
    destinationName: "Bohinj",
    price: 22.0,
    compareAtPrice: 25.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=1200&h=800&fit=crop&q=80"]),
    stock: 30,
    weight: 1050,
    organic: false,
    handmade: true,
    shippingFree: true,
    shipsEurope: true,
    shipsWorldwide: false,
    plan: "free",
    featured: false,
    verified: true,
    rating: 4.6,
    reviewCount: 98,
    sellerName: "Sirarna Bohinj",
    sellerEmail: "info@sirarna-bohinj.si",
  },
  {
    name: "Oljčno olje Slovenska Istra 0.5l",
    slug: "oljno-olje-slovenska-istra-05l",
    description: "Deviško oljčno olje iz Slovenske Istre. Hladno stiskano, z nizko kislostjo.",
    longDescription: "Ekstra deviško oljčno olje iz sort Istrska belica, Leccino in Frantoio. Pridelano na terrasastih nasadih ob obali. Srednje intenzivno, s travnato-dišavnim okusom in rahlim poprom v grlu.",
    category: "oil",
    destinationId: "piran",
    destinationName: "Piran",
    price: 19.9,
    images: JSON.stringify(["https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=1200&h=800&fit=crop&q=80"]),
    stock: 60,
    weight: 700,
    organic: true,
    handmade: false,
    shippingFree: false,
    shipsEurope: true,
    shipsWorldwide: true,
    plan: "premium",
    featured: true,
    verified: true,
    rating: 4.9,
    reviewCount: 543,
    sellerName: "Oljarna Strunjan",
    sellerEmail: "info@oljarna-strunjan.si",
  },
  {
    name: "Prekmurska gibanica (cel pekač)",
    slug: "prekmurska-gibanica",
    description: "Tradicionalna prekmurska gibanica — pladenj z 8 kosii. Skuta, orehi, jabolka, mak, rozine.",
    longDescription: "Prekmurska gibanica je zaščitena tradicionalna slovenska sladica. Sestavljena iz več plasti: testo, skuta, orehi, jabolka, mak, rozine, testo. Pečena v pekaču, narezana na 8 kosov. Dostava naslednji dan.",
    category: "food",
    destinationId: "murska-sobota",
    destinationName: "Murska Sobota",
    price: 24.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=1200&h=800&fit=crop&q=80"]),
    stock: 15,
    weight: 1500,
    organic: false,
    handmade: true,
    shippingFree: false,
    shipsEurope: false,
    shipsWorldwide: false,
    plan: "free",
    featured: false,
    verified: false,
    rating: 4.7,
    reviewCount: 67,
    sellerName: "Slaščičarna Murska",
    sellerEmail: "info@slascicarna-murska.si",
  },
  {
    name: "Kranjska klobasa (par) — zaščitena",
    slug: "kranjska-klobasa-par",
    description: "Originalna kranjska klobasa z zaščiteno geografsko označbo. Par (2 kosi, ~500g).",
    longDescription: "Kranjska klobasa je zaščitena s certifikatom tradicionalnega ugleda. Iz svinjine (80%) in slanine (20%), oblikovana v naravno črevo. Dimljena nad bukovim lesom. Par (2 kosi, skupaj ~500g).",
    category: "food",
    destinationId: "kranjska-gora",
    destinationName: "Kranjska Gora",
    price: 9.9,
    images: JSON.stringify(["https://images.unsplash.com/photo-1528607929212-2636ec44253e?w=1200&h=800&fit=crop&q=80"]),
    stock: 100,
    weight: 550,
    organic: false,
    handmade: true,
    shippingFree: false,
    shipsEurope: true,
    shipsWorldwide: false,
    plan: "free",
    featured: false,
    verified: true,
    rating: 4.8,
    reviewCount: 312,
    sellerName: "Mesnica Carniola",
    sellerEmail: "info@mesnica-carniola.si",
  },
  {
    name: "Ročno pleteni copati (par)",
    slug: "rocno-pleteni-copati",
    description: "Tradicionalno pleteni volneni copati iz Gorenjske. Topli, naravni, trajni.",
    longDescription: "Ročno pleteni copati iz 100% slovenske ovčje volne. Tradicionalni vzorec iz Gorenjske. Naravno barvani. Topli pozimi, dihajo poleti. Idealni za dom in darilo.",
    category: "craft",
    destinationId: "bled",
    destinationName: "Bled",
    price: 29.0,
    compareAtPrice: 35.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=1200&h=800&fit=crop&q=80"]),
    stock: 25,
    weight: 400,
    organic: true,
    handmade: true,
    shippingFree: true,
    shipsEurope: true,
    shipsWorldwide: true,
    plan: "premium",
    featured: true,
    verified: true,
    rating: 4.9,
    reviewCount: 156,
    sellerName: "Pletilnica Triglav",
    sellerEmail: "info@pletilnica.si",
  },
];

const experiences = [
  {
    name: "Rafting na Soči — adrenalinski pol dan",
    slug: "rafting-na-soci",
    description: "Vodeni rafting po najbolj razburljivih odsekih Soče. 3 ure, vse oprema vključena.",
    longDescription: "Izkušeni vodniki vas popeljejo po smaragdni Soči skozi soteske in brzce. Vključeno: neopren, čoln, vesla, čelada, rešilni jopič. Primerno za začetnike in izkušene.",
    category: "adventure",
    destinationId: "soca",
    destinationName: "Reka Soča",
    pricePerPerson: 45,
    durationHours: 3,
    minGroupSize: 2,
    maxGroupSize: 8,
    languages: JSON.stringify(["sl", "en", "de", "it"]),
    meetingPoint: "Bovec center, pred turističnim informacijskim centrom",
    address: "Trg golobarskih žrtev 16, 5230 Bovec",
    images: JSON.stringify(["https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=1200&h=800&fit=crop&q=80"]),
    providerName: "Soča Rafting Bovec",
    providerEmail: "info@socarafting.si",
    providerPhone: "+386 5 389 6300",
    providerWebsite: "https://www.socarafting.si",
    plan: "premium",
    featured: true,
    verified: true,
    rating: 4.9,
    reviewCount: 1247,
    familyFriendly: true,
    accessibility: false,
    bookingCount: 3421,
  },
  {
    name: "Kulinarična tura po Ljubljani — 4 ure",
    slug: "kulinaricna-tura-ljubljana",
    description: "Vodena tura po 6 ljubljanskih restavracijah z degustacijo lokalnih jedi in vin.",
    longDescription: "Sprehod po starem mestnem jedru z vodnikom-gastronomom. 6 postankov: od tradicionalnih štrukljev do sodobne slovenske kuhinje. Vključeno 6 jedi + 3 vina. Skupina max 12 oseb.",
    category: "tasting",
    destinationId: "ljubljana",
    destinationName: "Ljubljana",
    pricePerPerson: 79,
    durationHours: 4,
    minGroupSize: 2,
    maxGroupSize: 12,
    languages: JSON.stringify(["sl", "en", "de"]),
    meetingPoint: "Prešernov trg, pred zmajevim mostom",
    address: "Prešernov trg, 1000 Ljubljana",
    images: JSON.stringify(["https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1200&h=800&fit=crop&q=80"]),
    providerName: "Ljubljana Food Tours",
    providerEmail: "info@ljfoodtours.si",
    providerPhone: "+386 1 234 5678",
    providerWebsite: "https://www.ljfoodtours.si",
    plan: "premium",
    featured: true,
    verified: true,
    rating: 4.8,
    reviewCount: 678,
    familyFriendly: true,
    accessibility: true,
    bookingCount: 2156,
  },
  {
    name: "Vzpon na Triglav — 2 dni vodeni pohod",
    slug: "vzpon-na-triglav-2-dne",
    description: "Dvodnevni vodeni vzpon na Triglav (2864m). Preko Triglavske koče, prenočišče vključeno.",
    longDescription: "Zahteven dvodnevni pohod na najvišji vrh Slovenije. Dan 1: vzpon do Triglavske koče (2515m). Dan 2: zgodnji start, vzpon na vrh, sestop. Zahteva dobro kondicijo in osnovno pohodniško izkušnjo. Vodnik certificiran UIAGM.",
    category: "outdoor",
    destinationId: "triglav",
    destinationName: "Triglav",
    pricePerPerson: 220,
    durationHours: 36,
    minGroupSize: 1,
    maxGroupSize: 4,
    languages: JSON.stringify(["sl", "en", "de", "it"]),
    meetingPoint: "Aljažev dom v Vratih",
    address: "Vrata 1, 4247 Mojstrana",
    images: JSON.stringify(["https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=1200&h=800&fit=crop&q=80"]),
    providerName: "Alpinist School Triglav",
    providerEmail: "info@triglav-alpinizem.si",
    providerPhone: "+386 1 200 5500",
    providerWebsite: "https://www.triglav-alpinizem.si",
    plan: "premium",
    featured: true,
    verified: true,
    rating: 5.0,
    reviewCount: 423,
    familyFriendly: false,
    accessibility: false,
    bookingCount: 892,
  },
  {
    name: "Degustacija vina v Vipavski dolini",
    slug: "degustacija-vina-vipava",
    description: "Obisk 3 vinogradov v Vipavski dolini z degustacijo 9 vin in lokalnimi sirevi.",
    longDescription: "Celodnevna tura po Vipavski dolini. 3 vinogradništva, vsak z 3 vini in prigrizki. Predstavitev postopka pridelave, oglede kleti. Prevoz vključen iz Ajdovščine.",
    category: "tasting",
    destinationId: "nova-gorica",
    destinationName: "Nova Gorica",
    pricePerPerson: 95,
    durationHours: 6,
    minGroupSize: 2,
    maxGroupSize: 10,
    languages: JSON.stringify(["sl", "en", "it", "de"]),
    meetingPoint: "Ajdovščina, pred turističnim informacijskim centrom",
    address: "Cankarjeva ulica 4, 5270 Ajdovščina",
    images: JSON.stringify(["https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=1200&h=800&fit=crop&q=80"]),
    providerName: "Vipava Wine Tours",
    providerEmail: "info@vipava-tours.si",
    providerPhone: "+386 5 300 1234",
    providerWebsite: "https://www.vipava-tours.si",
    plan: "premium",
    featured: false,
    verified: true,
    rating: 4.7,
    reviewCount: 234,
    familyFriendly: false,
    accessibility: true,
    bookingCount: 567,
  },
  {
    name: "Delavnica: izdelava kranjske klobase",
    slug: "delavnica-kranjska-klobasa",
    description: "3-urna delavnica izdelave tradicionalne kranjske klobase z mesarjem. Vključen izvod v klobase.",
    longDescription: "Vodena delavnica v tradicionalni mesnici. Spoznajte postopek izbire mesa, mletja, začinjanja in polnjenja klobas. Vsak udeleženec naredi in odnese 5 klobas. Degustacija s teranom na koncu.",
    category: "workshop",
    destinationId: "kranjska-gora",
    destinationName: "Kranjska Gora",
    pricePerPerson: 65,
    durationHours: 3,
    minGroupSize: 2,
    maxGroupSize: 6,
    languages: JSON.stringify(["sl", "en", "de"]),
    meetingPoint: "Mesnica Carniola, center",
    address: "Borovška cesta 99, 4280 Kranjska Gora",
    images: JSON.stringify(["https://images.unsplash.com/photo-1528607929212-2636ec44253e?w=1200&h=800&fit=crop&q=80"]),
    providerName: "Mesnica Carniola",
    providerEmail: "info@mesnica-carniola.si",
    providerPhone: "+386 4 580 1234",
    plan: "free",
    featured: false,
    verified: true,
    rating: 4.8,
    reviewCount: 89,
    familyFriendly: true,
    accessibility: true,
    bookingCount: 234,
  },
  {
    name: "Sprehod po Blejskem otoku s pletno vožnjo",
    slug: "blejski-otok-pletna",
    description: "Tradicionalna pletna vožnja do Blejskega otoka + ogled cerkve + kremšnita.",
    longDescription: "Tradicionalna pletna vožnja (40 min v vsako smer) do Blejskega otoka. Ogled cerkve Marijinega vnebovzetja z zvonikom (99 stopnic). Vključena tradicionalna kremšnita v slaščičarni na otoku. Skupina max 15 oseb.",
    category: "cultural",
    destinationId: "bled",
    destinationName: "Bled",
    pricePerPerson: 28,
    durationHours: 2,
    minGroupSize: 1,
    maxGroupSize: 15,
    languages: JSON.stringify(["sl", "en", "de", "it", "fr"]),
    meetingPoint: "Pristanišče pletn, Park Bled",
    address: "Cesta svobode 1, 4260 Bled",
    images: JSON.stringify(["https://images.unsplash.com/photo-1502989649865-81233767fe55?w=1200&h=800&fit=crop&q=80"]),
    providerName: "Pletna Bled",
    providerEmail: "info@pletna-bled.si",
    providerPhone: "+386 4 575 4000",
    providerWebsite: "https://www.pletna-bled.si",
    plan: "premium",
    featured: true,
    verified: true,
    rating: 4.7,
    reviewCount: 1567,
    familyFriendly: true,
    accessibility: false,
    bookingCount: 4523,
  },
  {
    name: "Jamska tura Postojna + Predjama — pol dan",
    slug: "postojna-predjama-tura",
    description: "Vodena tura po Postojnski jami in Predjamskem gradu. Prevoz vključen.",
    longDescription: "Celodnevna tura: Postojnska jama (1.5 ure z elektriknim vlakcem in peš) + Predjamski grad (1 ura). Vstopnine vključene. Vodnik slovensko/angleško. Odhod iz Postojne.",
    category: "tour",
    destinationId: "postojna",
    destinationName: "Postojnska jama",
    pricePerPerson: 49,
    durationHours: 5,
    minGroupSize: 2,
    maxGroupSize: 20,
    languages: JSON.stringify(["sl", "en", "de", "it"]),
    meetingPoint: "Postojnska jama, pred glavnim vhodom",
    address: "Jamska cesta 30, 6230 Postojna",
    images: JSON.stringify(["https://images.unsplash.com/photo-1542884748-2b87b36c6b90?w=1200&h=800&fit=crop&q=80"]),
    providerName: "Karst Tours Slovenia",
    providerEmail: "info@karst-tours.si",
    providerPhone: "+386 5 700 0100",
    providerWebsite: "https://www.karst-tours.si",
    plan: "free",
    featured: false,
    verified: true,
    rating: 4.6,
    reviewCount: 432,
    familyFriendly: true,
    accessibility: true,
    bookingCount: 1234,
  },
  {
    name: "Wellness dan v Rogaški Slatini",
    slug: "wellness-dan-rogaska",
    description: "Celodnevni wellness paket v Rogaški Slatini: bazeni, savune, masaža, Donat Mg.",
    longDescription: "Paket vključuje: celodnevni dostop do termalnega wellnessa (bazeni, savune, turška kopel), 30-minutna masaža, kosilo z lokalnimi jedmi, 1L Donat Mg. Zasebno sobo za počitek.",
    category: "wellness",
    destinationId: "rogaska",
    destinationName: "Rogaška Slatina",
    pricePerPerson: 119,
    durationHours: 8,
    minGroupSize: 1,
    maxGroupSize: 4,
    languages: JSON.stringify(["sl", "en", "de", "it"]),
    meetingPoint: "Grand Hotel Rogaška, recepcija",
    address: "Zdraviliški trg 1, 3250 Rogaška Slatina",
    images: JSON.stringify(["https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1200&h=800&fit=crop&q=80"]),
    providerName: "Grand Hotel Rogaška",
    providerEmail: "info@grand-hotel-rogaska.si",
    providerPhone: "+386 3 811 3000",
    providerWebsite: "https://www.rogaska.si",
    plan: "premium",
    featured: true,
    verified: true,
    rating: 4.8,
    reviewCount: 789,
    familyFriendly: true,
    accessibility: true,
    bookingCount: 1567,
  },
];

async function main() {
  console.log("🌱 Seeding products and experiences...");

  await db.product.deleteMany({});
  await db.experience.deleteMany({});

  for (const p of products) {
    await db.product.create({
      data: {
        ...p,
        viewCount: Math.floor(Math.random() * 3000) + 100,
        saleCount: Math.floor(Math.random() * 200) + 10,
      },
    });
    console.log(`  ✅ Product: ${p.name}`);
  }

  for (const e of experiences) {
    await db.experience.create({
      data: {
        ...e,
        viewCount: Math.floor(Math.random() * 4000) + 100,
      },
    });
    console.log(`  ✅ Experience: ${e.name}`);
  }

  // Nastavi nekaj listing-ov kot sponsored
  await db.listing.updateMany({
    where: { plan: { in: ["premium", "enterprise"] } },
    data: { sponsored: true, sponsoredUntil: new Date("2026-12-31") },
  });
  console.log(`  ✅ Sponsored: premium/enterprise listings marked`);

  const pCount = await db.product.count();
  const eCount = await db.experience.count();
  const sCount = await db.listing.count({ where: { sponsored: true } });
  console.log(`\n✨ Seeded ${pCount} products, ${eCount} experiences, ${sCount} sponsored listings!`);
}

main()
  .catch((e) => {
    console.error("❌ Seed error:", e);
    process.exit(1);
  })
  .finally(async () => {
    await db.$disconnect();
  });
